### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [cmu-sei/pharos#1]
I would like to point out that identifiers like “[`_APIGRAPH_H_`](https://github.com/cmu-sei/pharos/blob/f8d8059c0dfc250024d6e1a4f9d34124bf0279d8/libpharos/apigraph.hpp#L7 "Update candidate")” and “[`_MATCHERTAGS_HPP_`](https://github.com/cmu-sei/pharos/blob/f8d8059c0dfc250024d6e1a4f9d34124bf0279d8/libpharos/matchertags.hpp#L5 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by sei-mwd** [comment]
Should be fixed in the latest commit.
