### ISSUE TITLE
ooanalyzer crash + remarks

### ISSUE THREAD

**Issue by trou** [cmu-sei/pharos#11]
Hello,
I wanted to try OOanalyzer, using the docker file, here is the result:
```
OOAN[ERROR]: No new() methods were found.  Heap objects may not be detected.
OOAN[ERROR]: No delete() methods were found.  Object analysis may be impaired.
OPTI[INFO ]: Function analysis complete, analyzed 491 functions in 12.6402 seconds.
OOAN[FATAL]: Unable to start Prolog session.
OOAN[FATAL]: XSB Initialization Error: init_error/XSB configuration file /root/pharos/scripts/build/XSB/xsb-3.8.0/config/x86_64-unknown-linux-gnu/lib/xsb_configuration.P does not exist or is not readable by you.
Segmentation fault (core dumped)
```

Besides, getting pharos to run is a pain:
* building from source did not work (Z3 linking errors)
* the docker build took 2.5 hours

Maybe you could provide either: 
* static (or partially static) binaries
* pre-built docker images.

Also, is `OOAnalyzer.py` compatible with IDA 7 ?

**Comment by edmcman** [comment]
Can you elaborate on the "Z3 linking errors"?  We aren't aware of any problem building with Z3.

Unfortunately, the error you pasted above is a bug in our Docker image that we recently became aware of.  We delete all the source code from the container to save space, but as you can see that causes problems with XSB prolog.  I am working on a solution for this.  You can probably work around it by removing `rm -rf /root/pharos` and the `-reclaim` argument from the Dockerfile.

I do have unofficial pre-built docker images at `edmcman/pharos` for now.  Hopefully we'll get them moved more official soon.

I'm not sure if `OOAnalyzer.py` is compatible with IDA 7.  I'll get back to you on that.

**Comment by sei-ccohen** [comment]
There's a reasonable chance that the Z3 linking errors are related to the Z3 version, which has been updated several times since this release of Pharos.  Be sure to build against the recommended version of Z3:

https://github.com/Z3Prover/z3/tree/b81165167304c20e28bc42549c94399d70c8ae65

OOAnalyzer.py has been tested with IDA 7, but not IDA 7.2 (it may still work).

**Comment by edmcman** [comment]
We just fixed the bug that was causing the Prolog error.  You can either try to rebuild, or pull from `eschwartz/pharos` on Docker hub.

**Comment by trou** [comment]
Indeed the bug seems fixed ! Thanks.
Regarding OOanalyzer.py, if it works with IDA7, it should work with IDA 7.2.
