### ISSUE TITLE
OOAnalyzer documentation does not include directions for SWI prolog

### ISSUE THREAD

**Issue by FallenAvatar** [cmu-sei/pharos#110]
Basically title.

#97 and #90 seem related.

Obtained source using git clone to ~/pharos and followed the instructions from [Install](https://github.com/cmu-sei/pharos/blob/master/INSTALL.md)

Been working through [OORules Readme](https://github.com/cmu-sei/pharos/blob/master/share/prolog/oorules/README.md) and ran into this issue when trying to run 
`./share/prolog/oorules/oodebugrun-swipl ooprog-facts.P >ooprog.log`

Have gone back and rebuilt from source, ran tests and installed again. No reported errors anywhere.

Let me know what other information you might need to confirm.

**Comment by sei-eschwartz** [comment]
Can you `ls ./share/prolog/oorules/` and tell us what is there?

**Comment by FallenAvatar** [comment]
fallenavatar@AmysRig:~/pharos$ ls ./share/prolog/oorules/
CMakeLists.txt  complete.P  guess.P     logging.P                     oodebugrun-nortti.in         oodebugrun-swipl.in  oojson.P             progress_oosolver.P     results.P             rules.P     swihelp.P  validate.P
README.md       facts.P     index.P     logging_instrumentation.P     oodebugrun-profile.in        oodebugrun.in        oorulerun.in         progress_oosolver.xwam  rtti-report-swipl.in  setup.P     trigger.P  validate.xwam
check.P         final.P     initial.P   logging_instrumentation.xwam  oodebugrun-swipl-noguess.in  oointeractive.in     oovalidate-swipl.in  report.P                rtti-report.in        setup.xwam  util.P
class.P         forward.P   insanity.P  oodebugrun-noguess.in         oodebugrun-swipl-nortti.in   oojson-swipl.in      oovalidate.in        report.xwam             rtti.P                softcut.P   util.xwam

Sorry, it really doesn't format nicely here :/

**Comment by sei-eschwartz** [comment]
That is your source directory.  You need to run the command from your build directory and it should work.

**Comment by FallenAvatar** [comment]
Sorry about that, here you go:

> fallenavatar@AmysRig:~/pharos/build/share/prolog/oorules$ ll
> total 1134
> drwxrwxrwx 1 fallenavatar fallenavatar    512 Jun 19 18:02 ./
> drwxrwxrwx 1 fallenavatar fallenavatar    512 Jun 16 00:04 ../
> drwxrwxrwx 1 fallenavatar fallenavatar    512 Jun 16 00:04 CMakeFiles/
> -rw-rw-rw- 1 fallenavatar fallenavatar    311 Jun 16 00:04 CTestTestfile.cmake
> -rw-rw-rw- 1 fallenavatar fallenavatar   6988 Jun 16 00:04 Makefile
> -rw-rw-rw- 1 fallenavatar fallenavatar   1340 Jun 16 00:04 class.P
> -rw-rw-rw- 1 fallenavatar fallenavatar   5319 Jun 16 00:04 cmake_install.cmake
> -rw-rw-rw- 1 fallenavatar fallenavatar    857 Jun 16 00:04 complete.P
> -rw-rw-rw- 1 fallenavatar fallenavatar  10403 Jun 16 00:04 facts.P
> -rw-rw-rw- 1 fallenavatar fallenavatar  20358 Jun 16 00:04 final.P
> -rw-rw-rw- 1 fallenavatar fallenavatar  20094 Jun 16 00:04 forward.P
> -rw-rw-rw- 1 fallenavatar fallenavatar  62305 Jun 16 00:04 guess.P
> -rw-rw-rw- 1 fallenavatar fallenavatar   2961 Jun 16 00:04 index.P
> -rw-rw-rw- 1 fallenavatar fallenavatar  16093 Jun 16 00:04 initial.P
> -rw-rw-rw- 1 fallenavatar fallenavatar  11485 Jun 16 00:04 insanity.P
> -rw-rw-rw- 1 fallenavatar fallenavatar   2419 Jun 16 00:04 logging.P
> -rw-rw-rw- 1 fallenavatar fallenavatar   1667 Jun 16 00:04 logging_instrumentation.P
> -rwxrwxrwx 1 fallenavatar fallenavatar    229 Jun 16 00:04 oodebugrun*
> -rwxrwxrwx 1 fallenavatar fallenavatar    254 Jun 16 00:04 oodebugrun-noguess*
> -rwxrwxrwx 1 fallenavatar fallenavatar    209 Jun 16 00:04 oodebugrun-nortti*
> -rwxrwxrwx 1 fallenavatar fallenavatar    254 Jun 16 00:04 oodebugrun-profile*
> -rwxrwxrwx 1 fallenavatar fallenavatar    217 Jun 16 00:04 oointeractive*
> -rw-rw-rw- 1 fallenavatar fallenavatar  16416 Jun 16 00:04 oojson.P
> -rwxrwxrwx 1 fallenavatar fallenavatar    229 Jun 16 00:04 oorulerun*
> -rwxrwxrwx 1 fallenavatar fallenavatar    224 Jun 16 00:04 oovalidate*
> -rw-rw-rw- 1 fallenavatar fallenavatar    554 Jun 16 00:04 progress_oosolver.P
> -rw-rw-rw- 1 fallenavatar fallenavatar    563 Jun 19 18:02 progress_oosolver.log
> -rw-rw-rw- 1 fallenavatar fallenavatar    351 Jun 19 18:02 progress_oosolver.xwam
> -rw-rw-rw- 1 fallenavatar fallenavatar   9977 Jun 16 00:04 report.P
> -rw-rw-rw- 1 fallenavatar fallenavatar    947 Jun 19 18:02 report.log
> -rw-rw-rw- 1 fallenavatar fallenavatar 159894 Jun 19 18:02 report.xwam
> -rw-rw-rw- 1 fallenavatar fallenavatar  10527 Jun 16 00:04 results.P
> -rwxrwxrwx 1 fallenavatar fallenavatar    217 Jun 16 00:04 rtti-report*
> -rw-rw-rw- 1 fallenavatar fallenavatar  17051 Jun 16 00:04 rtti.P
> -rw-rw-rw- 1 fallenavatar fallenavatar 139196 Jun 16 00:04 rules.P
> -rw-rw-rw- 1 fallenavatar fallenavatar  27148 Jun 16 00:04 setup.P
> -rw-rw-rw- 1 fallenavatar fallenavatar    824 Jun 19 18:02 setup.log
> -rw-rw-rw- 1 fallenavatar fallenavatar 151891 Jun 19 18:02 setup.xwam
> -rw-rw-rw- 1 fallenavatar fallenavatar   1607 Jun 16 00:04 softcut.P
> -rw-rw-rw- 1 fallenavatar fallenavatar   1800 Jun 16 00:04 swihelp.P
> -rw-rw-rw- 1 fallenavatar fallenavatar  10322 Jun 16 00:04 trigger.P
> -rw-rw-rw- 1 fallenavatar fallenavatar   9064 Jun 16 00:04 util.P
> -rw-rw-rw- 1 fallenavatar fallenavatar    524 Jun 19 18:02 util.log
> -rw-rw-rw- 1 fallenavatar fallenavatar   6738 Jun 19 18:02 util.xwam
> -rw-rw-rw- 1 fallenavatar fallenavatar  14654 Jun 16 00:04 validate.P
> -rw-rw-rw- 1 fallenavatar fallenavatar    592 Jun 19 18:02 validate.log
> -rw-rw-rw- 1 fallenavatar fallenavatar  19567 Jun 19 18:02 validate.xwam

**Comment by sei-eschwartz** [comment]
I think I see what the problem is.  We didn't update our directions to specify where `swipl` is.  Try this:

`cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DXSB_ROOT=$XSB_LOCATION -DSWIPL_ROOT=$SWIPL_LOCATION ..`

You'll need to install SWI of course.  You can find commands to do that [here](https://github.com/cmu-sei/pharos/blob/master/scripts/build_prereqs.bash#L58)

**Comment by FallenAvatar** [comment]
Bingo. That fixed it. Working on the next step of my analysis now :)

Thanks.

**Comment by sei-eschwartz** [comment]
Glad to hear that fixed the problem.  I'm going to leave the issue open so we remember to fix the documentation.
