### ISSUE TITLE
[OOAN] Crash when decompiling PSVita elfs

### ISSUE THREAD

**Issue by CreepNT** [cmu-sei/pharos#113]
I'm currently trying to reverse a commercial PSVita game that is using C++ classes, so I decided to use OOAnalyzer. I first tried direct analysis and then tried to follow the `Analyzing Large Executable` guide, but I got greeted with the same error both times.

Is the fact this is a PSVita elf causing the problem or am I missing something ?

I'm using Docker on Windows *without WSL2*, using the pre-built Docker image linked in the repo's README.
[Here is the output of ooanalyzer and fn2hash.](https://github.com/cmu-sei/pharos/files/4846865/CRASH.txt)

**Comment by sei-ccohen** [comment]
It appears that the executable that you are trying to analyze uses an unsupported hardware architecture that is not supported by ROSE.   OOAnalyzer really only works on 32-bit Windows Portable EXecutable Microsoft Visual Studio files at this time.   Conceptually OOAnalyzer can be extended to additional architectures, but practically a lot of effort is required.  I'm sorry to say that OOAnalyzer is unlikely to help with analyzing your executable.

**Comment by CreepNT** [comment]
Alright, thanks for answering.
