### ISSUE TITLE
Error: free(): invalid next size (fast)

### ISSUE THREAD

**Issue by FallenAvatar** [cmu-sei/pharos#114]
Hello again, finally got step three working mostly. Just hit this error though.

> fallenavatar@AmysRig:~/win$ /usr/local/share/pharos/prolog/oorules/oodebugrun-swipl  FirefallClient-facts.P >FirefallClient.log
> free(): invalid next size (fast)
> /usr/local/share/pharos/prolog/oorules/oodebugrun-swipl: line 5:    89 Aborted                 (core dumped) /usr/local/bin/swipl -g "set_prolog_flag(stack_limit, $STACK_LIMIT),set_prolog_flag(table_space, $TABLE_SPACE),asserta(library_directory('$DIR')),assert(logLevel(6)),['$DIR/report.P'],assert(rTTIEnabled),psolve('${1}')."

Relevant file info:
> fallenavatar@AmysRig:~/win$ ll
> total 14551212
> drwxrwxrwx 1 fallenavatar fallenavatar        4096 Jun 28 16:41 ./
> drwxrwxrwx 1 fallenavatar fallenavatar        4096 Jun 13 00:25 ../
> drwxrwxrwx 1 fallenavatar fallenavatar        4096 Jun 13 16:19 Docs/
> -rwxrwxrwx 1 fallenavatar fallenavatar   202054202 Jun 19 10:08 FirefallClient-facts.P*
> -rwxrwxrwx 1 fallenavatar fallenavatar   126426181 Jun 18 11:10 FirefallClient.csv*
> -rwxrwxrwx 1 fallenavatar fallenavatar    40197848 Jun  6 14:12 FirefallClient.exe*
> -rwxrwxrwx 1 fallenavatar fallenavatar 13466966819 Jun 30 05:52 FirefallClient.log*
> -rwxrwxrwx 1 fallenavatar fallenavatar  1064789711 Jun 18 10:59 FirefallClient.ser*

I had upped the stack limit to 500GB and table space to 50GB. Let me know if you need any other info.

**Comment by sei-eschwartz** [comment]
It looks like a crash in SWI prolog, which I have never seen before.  Can you provide  the facts file that triggered it? I will see if I can reproduce the problem.

Sent from Workspace ONE Boxer

On Jun 30, 2020 4:41 PM, Amy Zala <notifications@github.com> wrote:

Hello again, finally got step three working mostly. Just hit this error though.

fallenavatar@AmysRig:~/win$ /usr/local/share/pharos/prolog/oorules/oodebugrun-swipl FirefallClient-facts.P >FirefallClient.log
free(): invalid next size (fast)
/usr/local/share/pharos/prolog/oorules/oodebugrun-swipl: line 5: 89 Aborted (core dumped) /usr/local/bin/swipl -g "set_prolog_flag(stack_limit, $STACK_LIMIT),set_prolog_flag(table_space, $TABLE_SPACE),asserta(library_directory('$DIR')),assert(logLevel(6)),['$DIR/report.P'],assert(rTTIEnabled),psolve('${1}')."

Relevant file info:

fallenavatar@AmysRig:~/win$ ll
total 14551212
drwxrwxrwx 1 fallenavatar fallenavatar 4096 Jun 28 16:41 ./
drwxrwxrwx 1 fallenavatar fallenavatar 4096 Jun 13 00:25 ../
drwxrwxrwx 1 fallenavatar fallenavatar 4096 Jun 13 16:19 Docs/
-rwxrwxrwx 1 fallenavatar fallenavatar 202054202 Jun 19 10:08 FirefallClient-facts.P*
-rwxrwxrwx 1 fallenavatar fallenavatar 126426181 Jun 18 11:10 FirefallClient.csv*
-rwxrwxrwx 1 fallenavatar fallenavatar 40197848 Jun 6 14:12 FirefallClient.exe*
-rwxrwxrwx 1 fallenavatar fallenavatar 13466966819 Jun 30 05:52 FirefallClient.log*
-rwxrwxrwx 1 fallenavatar fallenavatar 1064789711 Jun 18 10:59 FirefallClient.ser*

I had upped the stack limit to 500GB and table space to 50GB. Let me know if you need any other info.

**Comment by FallenAvatar** [comment]
I can do that, but the facts file is over 200MB, and this error happened after 4 days. If you still want it, have any preferences on where its uploaded?

**Comment by sei-eschwartz** [comment]
It should compress down pretty well since it is text. I don't care where you put it as long as I can access it.

Crashing after 4 days is not ideal 😐 The crash suggests that there is heap corruption.  Probably the best bet is to compile SWI with address sanitizer and run with that.  Hopefully the heap corruption occurs in less than 4 days...

I will try to do this, but I recommend you try as well.  Its a win win for you.  Either you don't trigger the bug and hopefully complete the run, or you reproduce the crash and we can hopefully go to the swi prolog maintainer for help.

Sent from Workspace ONE Boxer

On Jun 30, 2020 5:18 PM, Amy Zala <notifications@github.com> wrote:

I can do that, but the facts file is over 200MB, and this error happened after 4 days. If you still want it, have any preferences on where its uploaded?

**Comment by FallenAvatar** [comment]
Ok, I will look into recompiling SWI.

Facts File: https://drive.google.com/file/d/1YiIFzpnWSH-LQXKCxR_c2siODOmvkjdf/view?usp=sharing

**Comment by FallenAvatar** [comment]
Question, this program use many smaller dlls. Is there anything that can be done with apianalyzer and/or callanalyzer that can help the analysis go faster? or just in general in this case?

**Comment by sei-eschwartz** [comment]
Ok, I have SWI with ASAN running on your file and another.  :crossed_fingers:  You can delete the file if you want to reclaim your drive space.

I will save the question about apianalyzer and callanalyzer for @sei-ccohen or @sei-jgennari .

**Comment by JanWielemaker** [comment]
Curious to what this will bring ...  Note that for long runs you should build the system with profile guided optimization.  I see you talk about clang.   I never managed to get PGO to work with clang (at some point it seemed to work, but the result was in fact slower).  Is this a Mac?   Compiling with gcc-10 using PGO almost doubles the performance compared to clang.   Notably Xcode 11 performs severely worse than Xcode 10.   Unfortunately addresssanitizer will eat that advantage :(

**Comment by sei-eschwartz** [comment]
Using PGO is an interesting idea.  What did you profile it with? Test suite executions?

**Comment by JanWielemaker** [comment]
See `CMAKE.md` (which should be renamed as there is no alternative any longer).   The code benchmarked is in the `bench` git submodule.   It has very limited tabling benchmarks from the project that brought tabling to SWI-Prolog.   Notably incremental tabling is missing.  I don't know how much it will help to include that as well.  More benchmarks are welcome :)

In any case, using recent gcc versions the effect is quite noticeable, upto to about 30%

**Comment by sei-eschwartz** [comment]
@FallenAvatar Any luck?  I just got the following:

```
ERROR: -g set_prolog_flag(stack_limit, 500 000 000 000),set_prolog_flag(table_space, 500 000 000 000),asserta(library_directory('/home/eschwartz/pharos/build/share/prolog/oorules')),assert(logLevel(6)),['/home/eschwartz/pharos/build/share/prolog/oorules/report'],assert(rTTIEnabled),psolve('/dev/fd/63').: Stack limit (465.7Gb) exceeded
ERROR:   Stack sizes: local: 46.8Gb, global: 31.9Gb, trail: 1.0Gb
ERROR:   Stack depth: 124, last-call: 7%, Choice points: 104,574,655
ERROR:   In:
ERROR:     [124] system:'$collect_findall_bag'(_108, [])
ERROR:     [122] system:setup_call_catcher_cleanup(<compound (:)/2>, <compound (:)/2>, _132, <compound (:)/2>)
ERROR:     [118] '$tabling':try_reeval(<trie>(0x71812470), <compound (:)/2>, <compound ret/2>)
ERROR:     [117] system:catch(<compound (:)/2>, deadlock, <compound (:)/2>)
ERROR:     [112] user:concludeMergeClasses(_238)
ERROR: 
ERROR: Use the --stack_limit=size[KMG] command line option or
ERROR: ?- set_prolog_flag(stack_limit, 1_000_000_000_000). to double the limit.
```

I will need to look more at why it is using so much memory.

**Comment by sei-eschwartz** [comment]
Breakdown of facts

```
      1 fileInfo
      1 % Object fact exporting complete.
      1 % Prolog facts autogenerated by OOAnalyzer.
      1 purecall
      5 symbolGlobalObject
     20 possibleVBTableWrite
    101 symbolProperty
    223 symbolClass
   2366 thunk
   4151 rTTIClassHierarchyDescriptor
   4151 rTTITypeDescriptor
   4709 rTTIBaseClassDescriptor
   4745 rTTICompleteObjectLocator
   5361 thisPtrAllocation
   6707 uninitializedReads
  17320 possibleVFTableWrite
  26162 thisPtrOffset
  44195 initialMemory
  46129 possibleVirtualFunctionCall
  57102 returnsSelf
  58394 funcOffset
 153586 noCallsAfter
 154208 noCallsBefore
 258046 funcReturn
 267761 thisPtrUsage
 299867 callReturn
 384604 funcParameter
 390721 callParameter
 409548 callTarget
 475147 methodMemberAccess
 924986 callingConvention
```

**Comment by sei-eschwartz** [comment]
As far as I can tell, the large amount of memory usage is from asserting a very, very large number of factNOTMergeClasses/2 facts.  I these come from concludeTrigger.  We probably need to break them up into multiple batches.

**Comment by sei-eschwartz** [comment]
![image](https://user-images.githubusercontent.com/50171988/86923552-331c3680-c0fc-11ea-84f1-af30d73baddd.png)

**Comment by sei-eschwartz** [comment]
Current suspicious is that the memory usage is from the heap.  Maybe to represent the very many `factNOTMergeClasses/2` terms?

**Comment by sei-eschwartz** [comment]
We actually let this run for a few weeks.  The good news is that it did not crash for us, but it also did not complete.  At some point, we'll try to circle back and see if we can improve the performance, but I don't know when we'll have time for that.

**Comment by sei-eschwartz** [comment]
We have made a number of performance improvements since this issue was created.  I suggest trying to rerun and reopening if there is still an issue.
