### ISSUE TITLE
Docker use ubuntu:latest cause error on package not exist

### ISSUE THREAD

**Issue by lprat** [cmu-sei/pharos#12]
Hi,

Your docker file use image of "ubuntu:latest" but i think than image changed since you make Dockerfile (xenial to bionic). Bionic version have packages that not disponible. For fix fastest, you change FROM ubuntu:latest to FROM ubuntu:xenial. 

Thanks
Lionel

**Comment by edmcman** [comment]
You caught this even more our weekly CI build did.  We'll fix it soon.

**Comment by edmcman** [comment]
Actually I just did a manual build and it worked fine.  Can you include a log of the problem you are encountering?

**Comment by lprat** [comment]
I'm really sorry, indeed, I deleted everything and I rebuild and it passes.
Excuse me for the time lost.

**Comment by lprat** [comment]
I'm really sorry, indeed, I deleted everything and I rebuild and it passes.
Excuse me for the time lost.

**Comment by edmcman** [comment]
No worries.  Let us know if you have any other issues.
