### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by screed59** [cmu-sei/pharos#13]
Hi. I tried to install all by your guides. I have tried docker and bash script. Both ways are failed. Can you please update scripts? 
For example, rose-develop is not downloaded correctly by GIt, only one file was downloaded, it says, that develop branch is not used, release shoud be used. I tried fix this, but in release ./build fails with "aclocal" and etc...

**Comment by edmcman** [comment]
Rose just changed their repository structure this week.  We haven't had a chance to update our build instructions and scripts yet, but we will do so soon.

**Comment by sei-eschwartz** [comment]
The scripts should all be updated now.  The only change was to point to the new repository.
