### ISSUE TITLE
This Pharos tools are so buggy !!! 

### ISSUE THREAD

**Issue by developeralgo8888** [cmu-sei/pharos#133]
Does not build or work . Why would anyone want a pre-built docker image ? When dealing with Code analysis you don't want a pre-built docker image. You need to be able to understand what is actually happening.

Decided to shelve this one . doesn't work .

**Comment by sei-ccohen** [comment]
You'll need to provide some more information about the actual problem if we're going to be able to help resolve it.   The build can be complicated, especially the ROSE dependency, but it works quite well for us any many others so there's probably something in your environment that we've not encountered before, or perhaps some subtle step in the build intructions were overlooked?
