### ISSUE TITLE
No json file after OOAnalyzer

### ISSUE THREAD

**Issue by dfdfdfs** [cmu-sei/pharos#146]
Hi, I have Ghidra 9.1.2. I downloaded the plugin OOAnalyzer Ghidra Plugin for Ghidra 9.1.2
https://github.com/sei-eschwartz/pharos/releases 

Installed it, the CERT button appeared.

But I can't find the json file.

Where is the json file saved? ? ?

**Comment by sei-eschwartz** [comment]
You need to run the ooanalyzer tool to produce the json file for your executable.  See [here](https://github.com/cmu-sei/pharos/blob/master/tools/ooanalyzer/ooanalyzer.pod) for documentation.

**Comment by dfdfdfs** [comment]
Is ooanalyzer suitable for elf arm analysis?

**Comment by sei-eschwartz** [comment]
No, there is no support for arm at all.  Sorry :(

**Comment by dfdfdfs** [comment]
Very sorry. Thanks.
