### ISSUE TITLE
Ghidra 9.2 - Plugin stalls when updating data types

### ISSUE THREAD

**Issue by 0xBEEEF** [cmu-sei/pharos#149]
In the recently released Ghidra 9.2 version, and when using the plugin released on 11/22, the following behavior occurs:

The first two import steps run without any problems. After that there is a step to update the datatypes. This always stops at 0 %. The log itself runs full and no progress can be seen. In the old 9.1.2 version, however, this step runs through without problems. 

In the log you can find the following messages, an error strangely enough not at first, but due to the misbehaviour the process cannot be finished completely, because the process always stops at 0 %.

![image](https://user-images.githubusercontent.com/36008527/99956297-18362000-2d86-11eb-9d76-57669ca0149c.png)

The line with the Clearing Component comes over and over again between the creation of the data types. This was not the case in the old version. My guess is that this leads to these problems. The data types are apparently already imported, but this Clearing Component makes the whole system so slow that you can't see the progress at all.

**Comment by sei-eschwartz** [comment]
That is an odd problem.  Can you provide a diff of part of the log between 9.1.2 and 9.2?

**Comment by sei-eschwartz** [comment]
On a very small example (2008/Debug/ooex5) I did not see any difference in the number of Clearing component lines.  I'll try a larger file.

**Comment by 0xBEEEF** [comment]
> That is an odd problem. Can you provide a diff of part of the log between 9.1.2 and 9.2?

Theoretically yes, but the problem is that it is a very big example. Now I have already upgraded the old version. The import of the file (a lot of RTTI data) takes almost half a day in the old version...

In the new version I am much faster here. It's just very annoying that shortly before the end of the import of the data types something goes "wrong". Unfortunately I can't give you more detailed information here, because I didn't even find a hint in the log why the import takes so long at this one place.

**Comment by sei-eschwartz** [comment]
I haven't been able to reproduce this.  Is it possible that the last time you imported you didn't have the code for clearing the components, and so importing was a bit faster?

I will see how easy it is to add a counter for the data types.  There was a reason I didn't add this initially though.

**Comment by sei-eschwartz** [comment]
Give this a try for a progress indicator: https://dev.azure.com/seipharos/pharos/_build/results?buildId=272&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by 0xBEEEF** [comment]
Good news! The import worked in the end. It just took a very long time. In the example there were also over 6000 classes. It felt that the import was much slower than in the old Ghidra version. 

From there I can close the topic. Sorry, I was obviously too impatient here. But maybe with a few thousand classes you really have to wait a long time.

I'm sorry that I opened this issue too fast and reported something based on my impatience.

**Comment by sei-eschwartz** [comment]
Glad to hear it worked in the end.  Sorry it is so slow.  At some point we'll have to revisit import speed but I think our time is better spent trying to improve the analysis accuracy.
