### ISSUE TITLE
Stub new/delete operators need to be handled better

### ISSUE THREAD

**Issue by sei-eschwartz** [cmu-sei/pharos#151]
In a test program I created, 7461553B7014A7921AC39DBA12CCC3A7 is a hash of operator delete.

But we have this in known-hashes.hpp:

```
// 0x4fb6e0 in ../code/testcases/malware/malware-67b9be3c70653a48a239a380e697babc.exe
{"7461553B7014A7921AC39DBA12CCC3A7", "near near void * __cdecl operator new[](unsigned int) ", "??_U@YAPAXI@Z", "new[]"},
```

How did this happen?

**Comment by sei-eschwartz** [comment]
Ah, it's basically a stub.  

```
void __cdecl operator_delete(void *param_1,uint param_2)

{
  operator_delete(param_1);
  return;
}
```

**Comment by Trass3r** [comment]
https://code.woboq.org/gcc/libstdc++-v3/libsupc++/new_opv.cc.html
https://code.woboq.org/gcc/libstdc++-v3/libsupc++/del_opv.cc.html
https://code.woboq.org/gcc/libstdc++-v3/libsupc++/del_op.cc.html

Seems to be almost mandated:
https://en.cppreference.com/w/cpp/memory/new/operator_new

But then I'm not sure why we had crashes in the past when mistaking delete/delete[].

**Comment by edmcman** [comment]
> 2) Called by the array form of new[]-expressions to allocate all storage required for an array (including possible new-expression overhead). The standard library implementation calls version (1)

Yes, good catch.

> But then I'm not sure why we had crashes in the past when mistaking delete/delete[].

Maybe it was confusing versions of `delete`/`delete[]` that had a different number of parameters?

**Comment by Trass3r** [comment]
No I'm pretty sure it was using delete instead of delete[] and this worked with msvc back then but crashed on Linux/gcc. Maybe the implementations have changed.

**Comment by edmcman** [comment]
Oh, I thought you meant a problem in OOAnalyzer.

Well, just because `operator delete == ::operator delete[]` does not mean that the other code the compiler generates for `delete` and `delete[]` is the same.
