### ISSUE TITLE
Pharos Slow Build On Ubuntu 18.04

### ISSUE THREAD

**Issue by bama4** [cmu-sei/pharos#16]
I am attempting to build pharos in a VmWare Ubuntu 18.04 VM. The build takes over 1 day and then starts slowing down to the point where the VM freezes. I have 4 GB RAM and 250 GB hard drive for this VM. None of the builds have completed. I tried building on Ubuntu 16.04 as well and had the same issue.

**Comment by sei-eschwartz** [comment]
It sounds like you are running out of RAM.  Are you compiling more than one file at once?

**Comment by bama4** [comment]
I am running the script/build.bash file

**Comment by sei-eschwartz** [comment]
That should only compile one file at once.  I'm not sure what to suggest other than adding more memory to your machine.  We've definitely compiled Pharos using less than 4 GB of RAM though...

You could also use our pre-built Docker images: https://hub.docker.com/r/eschwartz/pharos/

**Comment by sei-ccohen** [comment]
Actually, the build.bash script defaults to NCPU=-1, which might result in parallel builds.   ROSE in particular has several source files that require approximately 4GB of RAM _each_ to compile, and it will fail in small VMs with limited memory.   I also recommend that you allocate more RAM, or be very attentive to your system resources during the build. While a full day seems a little excessive, it's in approximately the right order of magnitude (multiple hours) to build all of the depdendencies.   This can be addressed with a faster system and multiple processors, but only if there's sufficient RAM to support parallel builds.

**Comment by bama4** [comment]
Thank you. How much RAM is sufficient enough?

**Comment by sei-eschwartz** [comment]
@sei-ccohen Try `echo ${NCPU:-1}` :)
@bama4 I think 8 GB should be enough.

**Comment by bama4** [comment]
This was resolved when the RAM was increased to 12 GB
