### ISSUE TITLE
Test changes to reasonClassRelationship tabling on paper suite

### ISSUE THREAD

**Issue by sei-eschwartz** [cmu-sei/pharos#161]
> - dynamic factObjectInObject/3 as incremental.
> :- table reasonClassRelationship/2 as incremental.
> 
> reasonClassRelationship(DerivedClass, BaseClass) :-
>      reasonClassRelationship(DerivedClass, MiddleClass),
>      factObjectInObject(MiddleClass, BaseClass, _Offset),
>      MiddleClass \== BaseClass.
> reasonClassRelationship(DerivedClass, BaseClass) :-
>      factObjectInObject(DerivedClass, BaseClass, _Offset),
>      DerivedClass \== BaseClass.
> 
> Next I tried a non-tabled version:
> 
> reasonClassRelationship(DerivedClass, BaseClass) :-
>      reasonClassRelationship(DerivedClass, BaseClass, [DerivedClass]).
> 
> reasonClassRelationship(DerivedClass, BaseClass, _Visited) :-
>      factObjectInObject(DerivedClass, BaseClass, _Offset),
>      DerivedClass \== BaseClass.
> reasonClassRelationship(DerivedClass, BaseClass, Visited) :-
>      factObjectInObject(DerivedClass, MiddleClass, _Offset),
>      DerivedClass \== MiddleClass,
>      \+ memberchk(MiddleClass, Visited),
>      reasonClassRelationship(MiddleClass, BaseClass, [MiddleClass|Visited]).
> 
> This gives the results below.
> 
> Original (your code)
> % 2,111,813 inferences, 0.163 CPU in 0.164 seconds (99% CPU, 12992799 Lips)
> 
> Above (not tabled)
> % 3,156,048 inferences, 0.198 CPU in 0.198 seconds (100% CPU, 15929133 Lips)
> 
> Not sure what to think about this. Given the far lower memory usage I'm
> tempted to conclude tabling is barely useful. But, tabling also avoided
> the need for the hand crafted cycle protection (which is indeed needed).
> 
> Finally, using :- dynamic factObjectInObject/3 as
> (incremental,abstract(0)). Reduces the table memory requirement to about
> 1/3th and bumps to time to 0.214.
>

**Comment by sei-ccohen** [comment]
The differences were pretty negligible.
