### ISSUE TITLE
Error "Unable to find class" during json generation step

### ISSUE THREAD

**Issue by TheIronWolfModding** [cmu-sei/pharos#163]
Following the wiki to run OOAnlyzer, after step 4 got this error:

Unable to find class 0x66e2d4. Please report this error to the OOAnalyzer developers.

I have all logs saved, but how can I upload them privately?

**Comment by sei-eschwartz** [comment]
Hmm, so we just fixed a bug related to this on Feb 1 (#155).  Are you by any chance using the docker image on docker hub?  Apparently the rebuild failed so it's still not the latest version.  I just restarted the build of the image; hopefully it will work this time.

Assuming you are using the docker hub image, I would recommend either waiting for the new build to complete (~160 minutes from now) or build your own docker image from master.

If you are in fact using the latest version of pharos, please let me know and I'll investigate more.

**Comment by TheIronWolfModding** [comment]
I am using Docker Desktop, WSL, latest image downloaded.

I would gladly provide you with any logs you need, but please contact me privately for logs.  Thanks for your time.

**Comment by sei-eschwartz** [comment]
This is good news.  The docker image is out of date, so that is almost certainly the cause of this problem.

**Comment by TheIronWolfModding** [comment]
> 
> 
> This is good news. The docker image is out of date, so that is almost certainly the cause of this problem.

Nice!  May I ask if there are plans for it to be refreshed?  I am very eager to apply amazing findings by OOA to my project, but before I do that I would be nice to start with the most precise json possible.

**Comment by sei-eschwartz** [comment]
I just restarted the build a few hours ago.  If it doesn't run into any problems, it will complete within an hour and should update.  You can always build your own updated image though.

**Comment by TheIronWolfModding** [comment]
> 
> 
> I just restarted the build a few hours ago. If it doesn't run into any problems, it will complete within an hour and should update. You can always build your own updated image though.

Thank You.

I am not familiar with Gridle, so a bit lack of experience here.  

I imagine Docker Desktop will notify me of the new image?  Which step would you recommend restarting, or shall I restart them all?

**Comment by sei-eschwartz** [comment]
Not sure about Docker desktop, I don't use it.  I would keep an eye on https://hub.docker.com/repository/registry-1.docker.io/seipharos/pharos/tags?page=1&ordering=last_updated  Right now it says pushed "7 days ago".  When it is less than that you should be good to pull.  It's still building... it's taking longer than usual for some reason.

You can also try [https://github.com/cmu-sei/pharos/blob/master/INSTALL.md#building-the-docker-image-easy](this) if you are impatient.

I don't know of any partitioning changes, so you could probably reuse your `.serialize` file.  But `.facts` generation changed slightly and `.results` generation changed quite a bit.  Obviously if you can, regenerating them all is the safest option.

**Comment by TheIronWolfModding** [comment]
Pulling new image, trying, will update this issue.

**Comment by sei-eschwartz** [comment]
Great.  Glad you saw the new image.

**Comment by TheIronWolfModding** [comment]
Now step 3 is running for 12hrs already, longer than before (was failing after around 6hrs).  So it is a progress :)

**Comment by sei-eschwartz** [comment]
Did it finish, or is it still running?

**Comment by TheIronWolfModding** [comment]
Updated build completed run cleanly :)  Thank you!
