### ISSUE TITLE
Error "Refusing to backtrack into reasoningLoop"

### ISSUE THREAD

**Issue by TheIronWolfModding** [cmu-sei/pharos#164]
Following the wiki to generate OOA .json, but this time removing ```--no-semantics --partitioner=rose``` for highest accuracy results.

During the step3, I hit this:

```
Refusing to backtrack into reasoningLoop to fix an upstream problem because backtrackForUpstream/0 is not set.

This likely indicates that there is a problem with the OO rules.

Please report this failure to the Pharos developers!
```

Have all logs for all steps saved.

**Comment by sei-eschwartz** [comment]
As with #163 I want to verify that you are actually running the latest version of Pharos.  Not that we think we fixed them all, but we did fix a number of bad rules that could lead to this message.  It's possible that if you were running on the previous version the new version might fix your problem.

**Comment by TheIronWolfModding** [comment]
I cannot run latest, because latest public Ghidra is 9.2.2, and I cannot lopad your latest plugin, which targets 9.3, right?

**Comment by TheIronWolfModding** [comment]
Updated build completed run cleanly :)  Thank you!
