### ISSUE TITLE
Enhancement: Ghidra plugin cannot match methods on rebased project

### ISSUE THREAD

**Issue by TheIronWolfModding** [cmu-sei/pharos#165]
I wanted to suggest an enhancemet for OOA Ghidra plugin:

* My ghidra project is rebased, meaning I have base address set to 0x0.  After I import .json, member functions (methods) are missing.
* If I change base back, import works better, but there's another issue.  None of the functions I renamed (dozens and dozens of them) are matched by the plugin to a member function.  I will have to re-start my project, which is worth it, but it feels like something that can be fixed.

Thanks for the consideration and amazing tools.

**Comment by sei-eschwartz** [comment]
> * If I change base back, import works better, but there's another issue.  None of the functions I renamed (dozens and dozens of them) are matched by the plugin to a member function.  I will have to re-start my project, which is worth it, but it feels like something that can be fixed.

So if you rename a function, then OOAnalyzer fails to include it as part of the class?

> * My ghidra project is rebased, meaning I have base address set to 0x0.  After I import .json, member functions (methods) are missing.

I would assume we're matching functions based on absolute address, so it makes sense that it wouldn't find them after you rebase.  @sei-ccohen do you know how good Pharos is at detecting base addresses?

**Comment by TheIronWolfModding** [comment]
->So if you rename a function, then OOAnalyzer fails to include it as part of the class?
correct, it remains standalone and I am positive it is part of a class.

**Comment by sei-eschwartz** [comment]
Can you email me your .exe and .json file (the old one is fine) to eschwartz@cert.org?  And let me know which method is missing.

**Comment by TheIronWolfModding** [comment]
Done.

**Comment by sei-eschwartz** [comment]
Thanks, I got them.  I am going to look at this now.

**Comment by TheIronWolfModding** [comment]
Feel free to stay in touch via email.   Reverting base to original, applying OOA, and rebasing again is easy.  But porting my changes to fresh project will take a week... hopefully can be automated.  Thank you for looking.

**Comment by sei-eschwartz** [comment]
Ok, I've replicated the problem.  When the method is renamed, we do not change the method name (which I think is fine), but we also don't set the namespace, which normally includes the class.

**Comment by TheIronWolfModding** [comment]
while you are at it - could confirm please that rebasing back and forth does not interfere with the final results of OOA application?

Meaning:
Original project - Base 0 -> Base Default -> Apply OOA -> Base 0 is safe to do with OOA?

**Comment by sei-eschwartz** [comment]
I have never used Ghidra rebasing capability, so I can't say for sure.  But if it puts the project in the same state as the default base address, I don't see why it would cause any problems.

A quick way of testing would be the following:

Find ghidra's `application.log` file.  Delete it.  Create a new Ghidra project and import your json without rebasing.  Move/rename the `application.log` file.

Then create a new Ghidra project with your modified base address, rebase to the default address, and import the json.

If you see roughly the same number of debug messages between the two log files, everything is probably fine.  If you see different log messages, those might be worth looking into.

**Comment by sei-eschwartz** [comment]
I think I fixed it.  A branch with the fix is building [here](https://dev.azure.com/seipharos/pharos/_build/results?buildId=317&view=results).  When it completes, you should be able to download the updated extension `.zip` file and install it in Ghidra.

**Comment by sei-eschwartz** [comment]
https://artprodcus3.artifacts.visualstudio.com/A93a5af2e-2d0d-479f-96c9-310295c06402/c3b15b4e-4ced-46ba-ab6b-0b2eaa348754/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3NlaXBoYXJvcy9wcm9qZWN0SWQvYzNiMTViNGUtNGNlZC00NmJhLWFiNmItMGIyZWFhMzQ4NzU0L2J1aWxkSWQvMzE3L2FydGlmYWN0TmFtZS9CdWlsZE9PQW5hbHl6ZXJHaGlkcmFQbHVnaW4uZ2hpZHJhOTIy0/content?format=file&subPath=%2Fghidra_9.2.2_PUBLIC_20210208_OOAnalyzerPlugin.zip

**Comment by TheIronWolfModding** [comment]
Tried that, but I do not think it worked.  All of my  renamed functions are still thiscall, not associated with any of the classes.

**Comment by TheIronWolfModding** [comment]
I tried minimal repro - renamed function at 549660 (default base) and applied OOA.  It stayed as free function.   But if I don't rename it it is part of a class:

```
                             *************************************************************
                             *                           FUNCTION                          
                             *************************************************************
                             undefined4  __thiscall  meth_0x549660 (cls_0x5d5b10 *  this )
             undefined4        EAX:4          <RETURN>
             cls_0x5d5b10 *    ECX:4 (auto)   this
             undefined4        Stack[-0x8]:4  local_8                                 XREF[1]:     005496b8 (*)   
                             OOAnalyzer::cls_0x5d5b10::meth_0x549660         XREF[1]:     meth_0x4330e0:0043334f (c)   
        00549660 56              PUSH       ESI
```

**Comment by sei-eschwartz** [comment]
This is what I get:

```
                             **************************************************************
                             *                          FUNCTION                          *
                             **************************************************************
                             undefined __thiscall renamed(void * this)
             undefined         AL:1           <RETURN>
             void *            ECX:4 (auto)   this
             undefined4        Stack[-0x8]:4  local_8                                 XREF[1]:     005496b8(*)  
                             OOAnalyzer::cls_0x5d5b10::renamed               XREF[1]:     meth_0x4330e0:0043334f(c)  
                             renamed
        00549660 56              PUSH       ESI
                                                      $U12f0:4 = COPY ESI
                                                      ESP = INT_SUB ESP, 4:4
                                                      STORE ram(ESP), $U12f0:4
```

What do you get when you rename it?

**Comment by sei-eschwartz** [comment]
Also, did you restart Ghidra in between removing and installing the new version of the extension?

**Comment by TheIronWolfModding** [comment]
I did restart Ghidra - I wonder if this is user error, let me try one more time.

**Comment by sei-eschwartz** [comment]
I have run into a similar problem before but I don't recall the exact situation.  Is there a copy of the extension in the `.ghidra` directory maybe?

**Comment by TheIronWolfModding** [comment]
I searched everywhere I could - so far no luck.  There's this window for Installing Extensions, and I cannot check/uncheck OOAnalyzer.  If this is Windows machine you are on, where is .ghidra folder located for you?

I'll keep looking, sorry for wasting your time on this.

**Comment by sei-eschwartz** [comment]
Any luck?

**Comment by TheIronWolfModding** [comment]
I am not the type to disappear, just took time to make sure it works, an yes it does, that was an update failure :)  It resolves functions to renamed ones!

Thanks a lot - closing the issue.

**Comment by sei-eschwartz** [comment]
Great!  Let us know if you have any other problems/feedback.

**Comment by TheIronWolfModding** [comment]
Will try my best to provide something useful down the road.
One concern I have is with future updates.... Say you improve your tooling, but how to incrementally update the project without re-doing it?   It is not a trivial problem, and likely needs Ghidra changes.... but ability to diff in Plugin between existing and new json?  Although maybe it is an overkill.

I'll keep an eye for problematic patterns in my project.
