### ISSUE TITLE
Issue building Ghidra plugin

### ISSUE THREAD

**Issue by Magister-Machinis** [cmu-sei/pharos#166]
Hello,
When I attempt to build the ghidra plugin in anticipation of installation I recieve the below error from gradle, using gradle version 6.6.1. Any thoughts on what I'm missing would be appreciated as I have java 11 installed.

Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not target platform: 'Java SE 11' using tool chain: 'JDK 8 (1.8)'.

edit: forgot to mention I am attempting this in Remnux.
Thanks!

**Comment by sei-eschwartz** [comment]
This seems like a general gradle problem.  Maybe this helps?  https://stackoverflow.com/questions/18487406/how-do-i-tell-gradle-to-use-specific-jdk-version

We also have binaries of the Ghidra plugin available.

**Comment by Magister-Machinis** [comment]
Oh some prebaked binaries would be great. I must've missed them when I was looking around. Thanks!

**Comment by sei-eschwartz** [comment]
It's a little buried: https://github.com/cmu-sei/pharos/tree/master/tools/ooanalyzer/ghidra/OOAnalyzerPlugin

**Comment by Magister-Machinis** [comment]
That appears to have worked, thank you for your patience.
