### ISSUE TITLE
mysqlpump.exe missing possibleConstructor(0x4353c0), constructor for Mysql::Tools::Dump::Compression_zlib_writer

### ISSUE THREAD

**Issue by sei-eschwartz** [cmu-sei/pharos#169]

**Comment by sei-eschwartz** [comment]
We seem to be missing a resultsSelf fact for 0x4353c0.

**Comment by dimitrijejankov** [comment]
Thank you a lot for all the great work! I was busy with other things recently. I will check it out today :D
