### ISSUE TITLE
prebuilt binaries

### ISSUE THREAD

**Issue by Trass3r** [cmu-sei/pharos#17]
Would be nice to have. An occasional binaries drop as a Github release would be enough.

**Comment by Trass3r** [comment]
Looks like https://hub.docker.com/r/eschwartz/pharos is the answer.

**Comment by sei-ccohen** [comment]
Yes, Ed's Docker image is certainly one approach to obtaining binaries.  Because of the complexities in maintaining and distributing binary builds, we have not attempted to do so.

**Comment by Trass3r** [comment]
Certainly works 👍

**Comment by sei-ccohen** [comment]
Glad to hear it.  I'll close this issue.   If you have other questions, please let us know.

**Comment by Trass3r** [comment]
Should be documented though.

**Comment by aldelaro5** [comment]
Actually, I never used docker before, but how do i obtain the binaries
inside my container to my host?

**Comment by Trass3r** [comment]
You could `docker pull eschwartz/pharos` and `docker run -it --rm -v .:/mnt/host eschwartz/pharos` and then copy files to /mnt/host.

**Comment by sei-ccohen** [comment]
Thanks for answering that question Trass3r, one of the reasons that we haven't said more about the docker image in the official documentation is because I'm not very familiar with docker yet, and I haven't wanted to commit Ed to maintaining the Docker image.  We'll revisit that issue and possible say more about it in the next release.

**Comment by MagnificentS** [comment]
> You could `docker pull eschwartz/pharos` and `docker run -it --rm -v .:/mnt/host eschwartz/pharos` and then copy files to /mnt/host.

Is it possible to use docker without an installation?

**Comment by Trass3r** [comment]
What do you mean? Open the image without docker? I don't think so.
Those are Linux binaries. You may be able to run them in WSL once extracted.

**Comment by MagnificentS** [comment]
I installed it on my pc but I need to restart (But I cannot).

**Comment by sei-ccohen** [comment]
As Trass3r helpfully suggested, running OOAnalyzer form the Docker image is also possibility, but I'm not a Docker expert so I can't really help you much there.

**Comment by sei-ccohen** [comment]
Our new release has improved the visibility of the Docker approach, and we're more invested in that now, so prebuilt binaries should be much easier to obtain.  I'm going to mark this issue closed, but folks are welcome to open a new issue if they're still finding the availability of prebuilt binaries to be a problem.
