### ISSUE TITLE
Partitioner killed while writing serialization data

### ISSUE THREAD

**Issue by apoxhu** [cmu-sei/pharos#189]
Trying to run [step-by-step analysis](https://github.com/cmu-sei/pharos/tree/master/share/prolog/oorules) on a fairly large 64 bit application, but can't even write serialized partition data - process seems to be killed by unknown reason right before finishing the serialized data.  Tried to run serialize with -v 9 (above 9 it becomes too slow) but no information given.

My command line is
`partition --serialize=ooprog.ser --maximum-memory=128000 --no-semantics --partitioner=rose --allow-64bit --partitioner-timeout 1000000 --threads=0 -v 9 ooprog.exe`

Output is
```
OPTI[WHERE]: Verbose logging level set to 9.
OPTI[INFO ]: Analyzing executable: ooprog.exe
PART[INFO ]: Using the standard ROSE function partitioner.
PART[INFO ]: Semantic control flow analysis disabled, analysis may be less correct.
PART[INFO ]: Marked entry point address 0x140B449F8 in segment ooprog.exe(.text) as executable.
OPTI[WARN ]: Non 32-bit Windows PE support is still highly experimental for this tool!
OPTI[INFO ]: Function partitioning took 96.561 seconds.
OPTI[INFO ]: Writing serialized data to "ooprog.ser".
Killed
```

**Comment by apoxhu** [comment]
Traced back the source of the problem to be Docker itself, with some new settings I experience a different kind of issue.
Seems like writing the data has come to an endless loop. After waiting ~30-40min I terminated the script, and the output file became the same size as when it was "Killed" before (~200mb), which took only 5-10min - but file is still not finalized.

Docker is now run by
`docker run --rm -it -v C:/ghidra/pharos:/pharos --memory=12g --memory-swap=128g --oom-kill-disable seipharos/pharos`

**Comment by sei-eschwartz** [comment]
I see that you are only assigning 12GB of ram to the docker container.  Is it running out of memory and swapping?  If so, it may take an extremely long time.

**Comment by apoxhu** [comment]
Yes it definitely is swapping, before assigning I saw the process using windows' virtual memory on my HDD, with --memory-swap it started using the vhd on my SSD so it (in theory) became much faster. 
But the process of partitioning was relatively fast, why would the writing take much more time? 

Also I'm trying to run ooanalyzer --no-semantics --partitioner=rose in the current context and so far it seems to be working flawlessly (Function analysis: 91% ATM)

**Comment by sei-eschwartz** [comment]
My guess is that it's using a lot of memory to compress the information, but I am not sure.  @sei-mwd may have a better idea.

**Comment by sei-ccohen** [comment]
The fact that your program is 64-bit means that OOAnalyzer will probably NOT work.

There's a control flow graph generation step right after partitioning that's often quite fast (just a few seconds) but has some bad performance issues on very large programs, and consumes a fair bit more RAM.   If you've got a large program and you're low on RAM that could be aggravating this bug^D^D^Dfeature of OOAnalyzer.  

I'm glad that --partitioner=rose is working "better" for you, but it's quite likely that this is partially because the ROSE partitioner found a lot fewer functions, and so there's just a lot less analysis to conduct.

**Comment by sei-eschwartz** [comment]
Oops.  I did not catch that it was a 64 bit binary.

**Comment by sei-eschwartz** [comment]
I am going to close this since I'm not sure there's much we can do.
