### ISSUE TITLE
Small error in documentation

### ISSUE THREAD

**Issue by janbbeck** [cmu-sei/pharos#196]
This file:
`https://github.com/cmu-sei/pharos/blob/master/tools/ooanalyzer/ooanalyzer.pod`
 states that 
"OOAnalyzer has been tested primarily with 32-bit Windows executables. 64-bit executables, and executables for other operating systems may work as well, but have not been tested extensively."
When I try to run something other than windows executables, I get the following message:
`
OOAN[FATAL]: This tool only suppports Windows Portable (PE) executable files.
`
So the mention of other operating systems should be removed. Or maybe there is a way to analyze linux binaries?

**Comment by sei-eschwartz** [comment]
Thanks, we'll update the documentation.  We eventually made analyzing non-Windows binaries an error because too many people were trying it and it really doesn't work.
