### ISSUE TITLE
bug: vftables are needed for each class inherited in its hierarchy, not just immediate bases

### ISSUE THREAD

**Issue by sei-eschwartz** [cmu-sei/pharos#207]
There is a bug in reasonVFTableBelongsToClass: https://github.com/cmu-sei/pharos/blob/master/share/prolog/oorules/rules.pl#L947

The problem is that a class needs a vftable for each class inherited in its hierarchy.  So if class A inherits from B, which inherits from C and D, then A needs at least two vftables, even though it only directly inherits from one class. 

This first came to light in #187.

**Comment by sei-eschwartz** [comment]
This is resolved in #214

**Comment by edmcman** [comment]
https://github.com/cmu-sei/pharos/blob/e14b16e99bfdc9ab4a79a74e3a7b7c888fdea1b1/share/prolog/oorules/rules.pl#L947
