### ISSUE TITLE
reasonClassSizeGTE_D is buggy

### ISSUE THREAD

**Issue by Trass3r** [cmu-sei/pharos#209]
```
ooprolog --facts DK2.facts.pl --results DK2.results.pl <

Consistency checks failed.
insanityClassSizeInvalid failed: Class=0x66eca4 LTESize=0x84 GTESize=0xb0
Initial sanity check failed, indicating the OO rules are incorrect.
Please report this failure to the Pharos developers!
  [29] prolog_stack:get_prolog_backtrace(100,[frame(29,clause(<clause>(0x55fc298618b0),6),_24981518)|_24981506],[goal_term_depth(100)]) at /usr/local/lib/swipl/library/prolog_stack.pl:134
  [28] throw_with_backtrace(error(system_error(initialSanityChecks))) at /usr/local/share/pharos/prolog/oorules/util.pl:185
  [26] solve_internal at /usr/local/share/pharos/prolog/oorules/setup.pl:659
```
[Facts](https://gist.github.com/Trass3r/e3d17d5fdd0b0b8d006bd3b5967c953b)

Even when using the `purecall(0x634d60).` hack from #139. Still the same testbed.

**Comment by sei-eschwartz** [comment]
I was able to reproduce this, thanks.

**Comment by sei-eschwartz** [comment]
Some additional logging:

```
reasonClassSizeGTE_D(0x670374, 0x18, 0x591820, sv_5533142198173699050, 0x591bf0).
reasonClassSizeGTE_D(0x670374, 0x1c, 0x591820, sv_10413347185328835298, 0x591bf0).
```

**Comment by sei-eschwartz** [comment]
I think I know what is happening.  The function 0x591820 is allocating either a CEngineSurface or a CEngineCompressedSurface.  Both of these inherit from CEngineSurfaceBase, whose constructor is 0x591bf0.

So, this seems to be a counter-example for reasonClassSizeGTE_D.  If a function allocates two classes that have a common base, but the classes have a different allocation size, it will cause GTE_D to fail.

But we already have a clause to deal with this: https://github.com/cmu-sei/pharos/blob/master/share/prolog/oorules/rules.pl#L3222

```
    % ejs 1/5/21: This rule only applies if we know there are no base classes using some of the
    % allocated object's space.
    factClassHasNoBase(Class),
```

`factClassHasNoBase(Class)` means that `Class` has no base classes.  This is true for `CEngineSurfaceBase`.  Unfortunately, I think we meant that there are no classes _derived_ from `Class`.  Unfortunately, we don't really have a fact for this.  But maybe we need one.  This specific example is an easier case because we have RTTI, so we can presumably look at that to determine there are no derived classes.

@sei-ccohen What do you think?

**Comment by sei-eschwartz** [comment]
@Trass3r As a workaround, you could try to remove one of or both of the thisPtrAllocation facts I posted above.

**Comment by Trass3r** [comment]
@sei-eschwartz doesn't seem to make a difference?

**Comment by sei-eschwartz** [comment]
You are right, there appears to be at least one other problem when those are commented out.  I'll play with it some more today.

**Comment by sei-eschwartz** [comment]
Here is the error I get when I comment those out:

insanityClassSizeInvalid failed: Class=0x66ed14 LTESize=0x70 GTESize=0xb0

0x66ed14 is apparently the vftable for the CGadget class.

This is what IDA has to say about 0x66ed14:

```
.rdata:0066ED14 ; const CGadget::`vftable'
.rdata:0066ED14 ??_7CGadget@@6B@ dd offset ??_Gfacet@locale@std@@UAEPAXI@Z_2
.rdata:0066ED14                                         ; DATA XREF: sub_52B810+1C↑o
.rdata:0066ED14                                         ; std::locale::facet::`scalar deleting destructor'(uint)+9↑o ...
.rdata:0066ED14                                         ; std::locale::facet::`scalar deleting destructor'(uint)
```

```
reasonClassSizeGTE_D(0x66ed14, 0xb0, 0x52a0d0, sv_6768039204246569279, 0x52b810).
reasonClassSizeGTE_D(0x66ed14, 0xb0, 0x52b390, sv_2626095382409969213, 0x52b810).
```

0x52b810 is CGadget::CGadget.  It looks like 0x52a0d0 constructs a CButton, which inherits from CGadget.  So same problem.

**Comment by sei-eschwartz** [comment]
@Trass3r For now you may just want to disable the problematic rules:

```
diff --git a/share/prolog/oorules/rules.pl b/share/prolog/oorules/rules.pl
index 3c02dffd..a9411d99 100644
--- a/share/prolog/oorules/rules.pl
+++ b/share/prolog/oorules/rules.pl
@@ -3228,7 +3228,7 @@ reasonClassSizeGTE(Class, Size) :-
     or([reasonClassSizeGTE_A(Class, Size),
         reasonClassSizeGTE_B(Class, Size),
         reasonClassSizeGTE_C(Class, Size),
-        reasonClassSizeGTE_D(Class, Size),
+        %reasonClassSizeGTE_D(Class, Size),
         reasonClassSizeGTE_E(Class, Size),
         reasonClassSizeGTE_F(Class, Size),
         reasonClassSizeGTE_G(Class, Size)
@@ -3281,7 +3281,7 @@ reasonClassSizeGTE_D(Class, Size) :-
     factClassHasNoBase(Class),
     % Debugging
     logtraceln('~@~Q.', [not((factClassSizeGTE(Class, ExistingSize), ExistingSize >= Size)),
-                         reasonClassSizeGTE_D(Class, Size)]).
+                         reasonClassSizeGTE_D(Class, Size, Function, ThisPtr, Constructor)]).
 
 % The given class is certain to be of this size or greater.  The reasoning for this rule is
 % that if we're certain that there's a member at a given offset and size, then the object must
@@ -3345,7 +3345,7 @@ reasonClassSizeLTE(Class, Size) :-
     %logwarnln('Recomputing reasonClassSizeLTE...'),
     or([reasonClassSizeLTE_A(Class, Size),
         reasonClassSizeLTE_B(Class, Size),
-        reasonClassSizeLTE_C(Class, Size),
+        %reasonClassSizeLTE_C(Class, Size),
         reasonClassSizeLTE_D(Class, Size)
       ]).
 
```

This does get past initial reasoning at least.  It's still running for me.

**Comment by Trass3r** [comment]
> ```
> .rdata:0066ED14 ; const CGadget::`vftable'
> .rdata:0066ED14 ??_7CGadget@@6B@ dd offset ??_Gfacet@locale@std@@UAEPAXI@Z_2
> .rdata:0066ED14                                         ; DATA XREF: sub_52B810+1C↑o
> .rdata:0066ED14                                         ; std::locale::facet::`scalar deleting destructor'(uint)+9↑o ...
> .rdata:0066ED14                                         ; std::locale::facet::`scalar deleting destructor'(uint)
> ```

Yeah the `locale` things should be due to ICF I think, a bit misleading.

**Comment by sei-eschwartz** [comment]
Neat, we knew about ICF but not exactly what it was called.  @sei-ccohen https://docs.microsoft.com/en-us/cpp/build/reference/opt-optimizations?view=msvc-170

**Comment by sei-eschwartz** [comment]
`reasonConstructor_A(0x5b88c0)`

```
Concluding factMethod(0x5b88c0).
reasonNOTVFTable_A(0x5b88c0).
Concluding factNOTVFTable(0x5b88c0).
reasonNOTVFTable_A(0x5b88c0).
reasonNOTConstructor_F(0x5b88c0, 0x5d91e0).
Concluding factNOTConstructor(0x5b88c0).
reasonNOTDeletingDestructor_E(0x5b88c0, 0x5d90c0).
reasonNOTDeletingDestructor_E(0x5b88c0, 0x5d91e0).
reasonNOTDeletingDestructor_F(0x5b88c0).
```

```
.text:005D91E0 sub_5D91E0      proc near               ; CODE XREF: sub_5D8B10+133↑p
.text:005D91E0                                         ; sub_5D8B10+231↑p ...
.text:005D91E0
.text:005D91E0 arg_0           = byte ptr  4
.text:005D91E0
.text:005D91E0                 push    esi
.text:005D91E1                 mov     esi, ecx
.text:005D91E3                 call    j_problem_method
.text:005D91E8                 test    [esp+4+arg_0], 1
.text:005D91ED                 jz      short loc_5D91F8
.text:005D91EF                 push    esi             ; Block
.text:005D91F0                 call    ??3@YAXPAX@Z    ; operator delete(void *)
.text:005D91F5                 add     esp, 4
.text:005D91F8
.text:005D91F8 loc_5D91F8:                             ; CODE XREF: sub_5D91E0+D↑j
.text:005D91F8                 mov     eax, esi
.text:005D91FA                 pop     esi
.text:005D91FB                 retn    4
.text:005D91FB sub_5D91E0      endp
```

`j_problem_method` is a thunk to:
```
.text:005B88C0 destructor_calls_delete proc near       ; CODE XREF: sub_555CC0+244↑p
.text:005B88C0                                         ; sub_55C3C0+102↑p ...
.text:005B88C0                 mov     eax, [ecx+8]
.text:005B88C3                 mov     dword ptr [ecx], offset sure_looks_like_a_vtable
.text:005B88C9                 push    eax             ; Block
.text:005B88CA                 call    ??3@YAXPAX@Z    ; deletes ecx+8
.text:005B88CF                 add     esp, 4
.text:005B88D2                 retn
.text:005B88D2 destructor_calls_delete endp
```

0x5b88c0 and 0x5d91e0 are both kind of weird.  0x5d91e0 more so.  It calls delete on the pointer at offset 8.  So it's not a regular deleting destructor.

Anyway, let me summarize:

- We decide that 0x5b88c0 has to be a constructor or destructor because it installs a vftable.  (This is a bad assumption to start with, but it might be right.)
- We decide 0x5d91e0 is a deleting destructor because it calls delete.
- We decide 0x5b88c0 is not a constructor because 0x5d91e0 is not a constructor because it is a deleting destructor.

But we also conclude:
- 0x5b88c0 is not a deleting destructor because it does not call delete on itself.  It does call delete, but on a different pointer.
- Therefore 0x5b88c0 is a constructor?

Why can't 0x5b88c0 be a real destructor?  Trying to figure that out.

**Comment by sei-eschwartz** [comment]
Because pharos' static analysis decided it can't be

**Comment by sei-eschwartz** [comment]
I am running again here, but it would help @trass3r if you have the facts log file and could look for the message that says:

`OOAN[INFO ]: Method 0x005B88C0 is NOT a destructor because of the call at 0xXXXX`

**Comment by sei-eschwartz** [comment]
Hmm.  I just ran and I do have a `noCallsAfter(0x5b88c0)` fact, but you don't.  What command line did you run to generate the facts file?

**Comment by sei-eschwartz** [comment]
I was able to run through with my .facts file and applying the patch I posted [above](https://github.com/cmu-sei/pharos/issues/209#issuecomment-1032712107).

[DKII-files.zip](https://github.com/cmu-sei/pharos/files/8027823/DKII-files.zip)

**Comment by Trass3r** [comment]
> What command line did you run to generate the facts file?

Don't have in front of me right now but should still be the same as in https://github.com/cmu-sei/pharos/issues/139#issuecomment-705855099
There are 2 new/delete pairs.

**Comment by sei-eschwartz** [comment]
I have made some progress on #212.  Testing it on DKII now.  Hopefully with #212 fixed and ClassSizeGTE_D commented out we'll be able to get a complete run through.

**Comment by sei-eschwartz** [comment]
With those changes I was able to do a complete run.  Note that the problem in ClassSizeGTE_D is still not fixed.

[DKII.zip](https://github.com/cmu-sei/pharos/files/8061417/DKII.zip)

**Comment by Trass3r** [comment]
Not sure if this is still related to the original problem but it still doesn't run through:

```
Contradictory information about constructor: factConstructor(0x5de050) but reasonNOTConstructor(0x5de050)
Constraint checks failed, retracting guess!
failed.
Consistency checks failed.
Contradictory information about constructor: factConstructor(0x600400) but reasonNOTConstructor(0x600400)
Constraint checks failed, retracting guess!
tryBinarySearch completely failed on [0x5de050] and will now backtrack to fix an upstream problem.
Refusing to backtrack into reasoningLoop to fix an upstream problem because backtrackForUpstream/0 is not set.
This likely indicates that there is a problem with the OO rules.
Please report this failure to the Pharos developers!
 [150] prolog_stack:get_prolog_backtrace(100,[frame(150,clause(<clause>(0x5ce281eb4d00),6),_5626440)|_5626428],[goal_term_depth(100)]) at /usr/local/lib/swipl/library/prolog_stack.pl:137
 [149] throw_with_backtrace(error(system_error(upstreamProblem))) at /usr/local/share/pharos/prolog/oorules/util.pl:185
  [26] solve_internal at /usr/local/share/pharos/prolog/oorules/setup.pl:681
  [25] catch(user:solve_internal,_5626664,user:((_5626732=error(resource_error(private_table_space),_5626746)->complain_table_space(ooscript);_5626796=error(resource_error(stack),_5626810)->complain_stack_size(ooscript);true),throw(_5626842))) at /usr/local/lib/swipl/boot/init.pl:562
  [24] solve(ooscript) at /usr/local/share/pharos/prolog/oorules/setup.pl:617
```

**Comment by sei-eschwartz** [comment]
Hopefully it is unrelated, I'll check it out. It could be #227. That binary reminded me of yours in a few ways.

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by edmcman** [comment]
Hopefully it's unrelated but I'll check it out.  It might be related to
#227.
