### ISSUE TITLE
Does pharos support ARM now?

### ISSUE THREAD

**Issue by tjzhou23** [cmu-sei/pharos#210]

**Comment by cfcohen** [comment]
I'm assuming that you saw this commit https://github.com/cmu-sei/pharos/commit/e14b16e99bfdc9ab4a79a74e3a7b7c888fdea1b1 and noticed the reference to ARM32 and Capstone.   So, yes, in some sense Pharos now has some ARM support.   But that support is definitely going to be limited to tools like fn2hash, fn2yara, dumpmasm, and serialize.   These are the tools that need little more than instruction disassembly and partitioning.  Basically these features were added by the ROSE developers, and we've done the minimal work to build correctly against that improvement.

The more interesting tools like OOAnalyzer are definitely not going to work, and I seriously doubt that any of the other tools will do anything useful.  There's a small chance some of the other tools might do something by dumb luck if the only thing different is the ARM architecture (e.g. it's an ARM MS Windows 32 PE executable).   To build a version with the *very* *untested* ARM support, first build ROSE using Capstone and then build Pharos as usual.   Please let us know if you learn anything interesting while testing it.
