### ISSUE TITLE
Cmake Compiling error

### ISSUE THREAD

**Issue by josuamanuel13** [cmu-sei/pharos#218]
-- Building for: Visual Studio 16 2019
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
-- The C compiler identification is MSVC 19.28.29913.0
-- The CXX compiler identification is MSVC 19.28.29913.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:6 (build_pharos_pod):
  Unknown CMake command "build_pharos_pod".
  -- Configuring incomplete, errors occurred!
  
  Env:
  Windows 10
  cmake version 3.22.0
  tring to build Last Version of OOAnalyzer

**Comment by sei-eschwartz** [comment]
I don't think anyone has ever tested building Pharos on Windows.  You are probably better off using the Docker image.

I'm not sure though why cmake would be failing like that.  @sei-mwd Do you have any ideas?

**Comment by sei-mwd** [comment]
Not certain what to say here.  The top level `CMakelists.txt` file has the following clause on line 21:
```
project(pharos CXX C)
```

This makes me think that you're probably not pointing CMake to the top-level pharos directory.  Can you provide more information on how CMake was invoked?

That said, I would not be surprised if a Windows build would fail regardless.  Although we've tried to avoid non-portable code, I do not believe we have fully succeeded in that.

**Comment by sei-eschwartz** [comment]
@josuamanuel13 Let us know if you have any other information.
