### ISSUE TITLE
Can't build latest master on ubuntu 22.04

### ISSUE THREAD

**Issue by rvanlaar** [cmu-sei/pharos#223]
The build fails during the scripts/build_prereqs.bash step.

Ran the following from INSTALL.md

```
$ sudo apt install build-essential wget flex ghostscript bzip2 \
  git subversion automake libtool bison python3 libncurses-dev \
  vim-common sqlite3 libsqlite3-0 libsqlite3-dev zlib1g-dev cmake \
  libyaml-cpp-dev libboost-all-dev libboost-dev libxml2-dev ninja-build
$ ./scripts/build_prereqs.bash
```

Build log can be found here: https://gist.github.com/rvanlaar/394b70394536f739c3938f768601817a

**Comment by sei-eschwartz** [comment]
Just noticed Ubuntu 22.04 in the title

**Comment by sei-eschwartz** [comment]
You can try a newer version of SWI: https://github.com/sei-eschwartz/pharos/commit/471f67cba254ea0a71c662c82bda4b2c84838327

**Comment by rvanlaar** [comment]
I tried to use the newer version. It has the same problem.

```
$ git clone --recursive -b V8.5.12 --depth 1 https://github.com/swi-prolog/swipl-devel
$ cd swipl-devel
$ mkdir build
$ cd build
$ cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DINSTALL_DOCUMENTATION=off ..
$ make
```
The problem is the same. 

Indeed ubuntu 22.04.
```
$ openssl version
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
```

**Comment by sei-eschwartz** [comment]
I just tried this and it worked for me.  Are you sure you have commit 5da003d0940ad997500e623b1d9f7c1eba30555c checked out?  If you do, please include a full log of the build.

**Comment by sei-eschwartz** [comment]
5da003d0940ad997500e623b1d9f7c1eba30555c is V8.5.12.  Please verify which commit you actually have checked out.

**Comment by rvanlaar** [comment]
Thank you for your patience. I tried it again. V8.5.12 is buildable.

**Comment by sei-eschwartz** [comment]
Cool.  I'm testing pharos with SWI 8.5.12, but assuming that works (it should), then we'll just update the recommended versions of SWI
