### ISSUE TITLE
WSL: cannot see file mapped

### ISSUE THREAD

**Issue by logunovFGP** [cmu-sei/pharos#256]
![image](https://github.com/cmu-sei/pharos/assets/109694383/9b1d56b1-3316-4424-872d-def116ee25af)

When container run under WSL Ubuntu 22.04 LTS, it cannot see the file mapped side by side to the calling path, fails with fatal error.

**Comment by sei-eschwartz** [comment]
This seems like it is a WSL problem.  Can you run a command like md5sum on your exe from WSL?
