### ISSUE TITLE
parallel analysis

### ISSUE THREAD

**Issue by Trass3r** [cmu-sei/pharos#26]
Would it be possible to parallelize the function analysis?
Even for an exe from the 90s with only 2-3MB it takes lots of hours.

**Comment by sei-ccohen** [comment]
We've done some work on parallelization.  Stay tuned for a new code release. ;-)

**Comment by Trass3r** [comment]
Hopefully that will make it more feasible to run the analysis :)

**Comment by cfcohen** [comment]
Don't set your expectations too high. :-)  It largely moves us from a runtime problem to a memory problem, and that's part of why I commented in another issue that we're working on memory as well.   Still, it can be several times faster when there's sufficient RAM.

**Comment by Trass3r** [comment]
True I checked, it's already memory-bound.

**Comment by Trass3r** [comment]
Thinking again, why would it (significantly) increase memory usage? It should just build up the memory faster.
Works like a charm!

**Comment by sei-ccohen** [comment]
For very large programs (say >10 thousand functions), we still end up running out of RAM.  Or perhaps we just need to try your trick of allocating a LOT of swap...
