### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by sudoLife** [cmu-sei/pharos#268]
Hi,

First, thank you for all your work!

I am trying out OOAnalyzer on a 5.6M 32-bit DLL using the guide for [large executables](https://github.com/cmu-sei/pharos/blob/master/share/prolog/oorules/README.md). I get a segfault on [step 2](https://github.com/cmu-sei/pharos/blob/master/share/prolog/oorules/README.md#step-two-object-oriented-analysis-of-functions) when trying to use the actual OOAnalyzer. 

My computer specs:
```
Linux Distribution:             Arch Linux
Linux Kernel:                   6.6.26-1-lts
Computer Model:                 TUXEDO TUXEDO Pulse 15 Gen1 Standard
Processor (CPU):                AMD Ryzen 7 4800H with Radeon Graphics
CPU Sockets/Cores/Threads:      1/8/16
Architecture:                   x86_64 (64-bit)
Total memory (RAM):             63720 MiB (63GiB) (66816 MB (67GB))
```

I tried using 128000, 57000 and 50000 memory parameter with 16, 16, and 4 threads, respectively, with the same result. I don't know if I am missing some calculation here. Maybe it was never meant to be used on DLLs? 

If you want me to debug this somehow, give me some pointers and I'll try my best :)

**Comment by sei-eschwartz** [comment]
We are investigating a concurrency problem in #267.  Can you try to run without `--threads=X` and see if the crash occurs?

**Comment by sudoLife** [comment]
> We are investigating a concurrency problem in #267. Can you try to run without `--threads=X` and see if the crash occurs?

Yes, I'm on it! Will update.

**Comment by sudoLife** [comment]
UPD: It's gotten to function analysis which it couldn't do before! Currently at 3%. I set memory to 57000. It has some errors like "analysis of functrion <address> failed: relative memory exceeded" and things like that but I assume that's just part of the process since it doesn't crash. 

I'll let you know if it gets to the end and thanks for such a prompt response!

**Comment by sei-eschwartz** [comment]
Great.  Sounds like pretty normal warnings.

________________________________________

**Comment by sudoLife** [comment]
Thanks, it finished! I guess we can close this issue, and I'll keep watch over the related bug.

Quick question, where is the readme for putting the results to Ghidra? [This](https://github.com/cmu-sei/pharos/blob/master/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/README.md) link from [this README section](https://github.com/cmu-sei/pharos/blob/master/share/prolog/oorules/README.md#step-five-load-the-json-into-ida-pro-andor-ghidra) is broken.

**Comment by sei-eschwartz** [comment]
That functionality was moved to https://github.com/certcc/kaiju

Thanks for telling us about the broken link, we'll get that fixed.
