### ISSUE TITLE
Prolog sanity check failed - multiple inheritance offsets

### ISSUE THREAD

**Issue by Detectronic-PB** [cmu-sei/pharos#275]
I'm getting this error trying to run OOProlog on a Kensington firmware update utility:

```
Consistency checks failed.
Class 0x587970 inherits from 0x569a4c at offsets 0 and 0x244
Initial sanity check failed, indicating the OO rules are incorrect.
```

There are several warnings/errors at the OOAnalyzer stage which may be related.
\
\
**Container Version**: seipharos/pharos:latest (sha256:fe09ad8e492115b7a1cfe0899995fa37057089d695d73332aa633b7f696f33bd)

**Input file**: [KensingtonUpdate.exe](https://www.kensington.com/siteassets/product-support/k64325-expert-mouse-support-page/expert-mouse-wired-v0116_1678293514.zip)

**API database JSON files**: [ApiJson.zip](https://github.com/user-attachments/files/17925614/ApiJson.zip)

**Logs**: [Logs.zip](https://github.com/user-attachments/files/17926282/Logs.zip)

**Partition command**:
```sh
partition
    --serialize=kensington/kensington-sem.ser
    --maximum-memory=10240
    kensington/KensingtonUpdate.exe
```

**Analyzer command**:
```sh
ooanalyzer
    --serialize=kensington/kensington-sem.ser
    --new-method=0x4116a6
    --new-method=0x4116d8
    --new-method=0x42f692
    --delete-method=0x42f6ae
    --delete-method=0x53b4c0
    --maximum-memory 18000
    --per-function-maximum-memory=0
    --prolog-facts=kensington/kensington-facts.pl
    --threads=1
    --per-function-timeout=600
    --apidb=/usr/local/share/pharos/contrib/winspool.json
    --apidb=kensington/hid.xml.json
    --apidb=kensington/gdiplus.xml.json
    --apidb=kensington/SetupAPI.xml.json
    --apidb=kensington/UxTheme.xml.json
    --apidb=kensington/Imm32.xml.json
    --apidb=kensington/Msimg32.xml.json
    --apidb=kensington/Oleacc.xml.json
    --apidb=kensington/User32.xml.json
    --apidb=kensington/OleDlg.xml.json
    kensington/KensingtonUpdate.exe
```

Note: --threads=1 is to avoid a multithread issue that I'll submit/add to another issue for.

**Prolog command**:
```sh
ooprolog
    --facts kensington/kensington-facts.pl
    --results kensington/kensington-results.pl
    --log-level=6
```

**Comment by sei-eschwartz** [comment]
Thanks, I will take a look at this.  The threading problem is probably #267.

**Comment by sei-eschwartz** [comment]
Working backwards...

```
Consistency checks failed.
Class 0x587970 inherits from 0x569a4c at offsets 0 and 0x244
```

```
Merging class 0x50b8db into 0x587970 ...
```

```
reasonMergeVFTables_A(constructor, 0x587970, 0x50b8db, 0x587970, 0, factVFTableWrite(0x50b8f8, 0x50b8db, 0, 0x587970)).
```

**Comment by sei-eschwartz** [comment]
```
[eschwartz@pd4 ooanalyzer-tests]$ /home/mwd/git/plogtrace/plogtrace.py ./code/testcases/kensington/kensington.exe.results.log 'factObjectInObject(0x587970, 0x569a4c, 0x244)'
1487178: Retracting factObjectInObject(0x50b8db, 0x569a4c, 0x244) and asserting factObjectInObject(0x587970, 0x569a4c, 0x244) ...
1487060: Merging class 0x50b8db into 0x587970 ...
895020: Retracting factObjectInObject(0x50b8db, 0x426738, 0x244) and asserting factObjectInObject(0x50b8db, 0x569a4c, 0x244) ...
894951: Merging class 0x426738 into 0x569a4c ...
152343: Concluding factObjectInObject(0x50b8db, 0x426738, 0x244).
```

```
reasonObjectInObject_D(0x50b8db, 0x426738, 0x244, validMethodCallAtOffset(0x50b92d, 0x50b8db, 0x426738, 0x244)).
```

``` prolog
% This rule is a special case of the reasonObjectInObject_E, that relies on the fact that it
% does not matter whether the InnerClass and OuterClass are provably different or whether
% they're just currently not assigned to the same class.  The key observation is that the
% distinction only matters when offset is non-zero, because that fact alone rules out the
% possibility that the two classes are in fact the same class.
```

**Comment by sei-eschwartz** [comment]
0x587970 is the vftable for .?AVCMFCPropertyGridCtrl@@
and 0x569a4c is the vftable for .?AVCWnd@@

**Comment by sei-eschwartz** [comment]
According to [this](https://learn.microsoft.com/en-us/cpp/mfc/reference/cmfcpropertygridctrl-class?view=msvc-170):

> class CMFCPropertyGridCtrl : public CWnd

So what is going on with the offset at 0x244?

**Comment by Detectronic-PB** [comment]
Just to add some more information in case it's relevant.

I identified 3 new operators and 2 delete operators, in a potentially strange configuration:
- 0x004116a6 is the main new operator
- 0x0053b4c0 is the main delete operator
- 0x004116d8 is a wrapper around the main new operator
- 0x0042f692 is CNoTrackObject::operator_new
- 0x0042f6ae is CNoTrackObject::operator_delete

Having double checked these just now I've found a wrapper for the main delete operator as well, I will try running again with that one defined.

**Comment by sei-eschwartz** [comment]
At 0x50b92d of 0x50b8db (probably MFCPropertyGridCtrl's constructor), we call 0x426738 at offset 0x244.

**Comment by sei-eschwartz** [comment]
I think the MFC classes in this program are triggered a rare-but-not-unknown problem in a sanity rule, insanityInheritTwice.  Comment out [this line](https://github.com/cmu-sei/pharos/blob/master/share/prolog/oorules/insanity.pl#L345) and try to run again.

**Comment by Detectronic-PB** [comment]
Initial results are promising, it's on to the guess phase.

As an aside, are any of the errors in the analysis log concerning? I'm assuming it will just result in slightly less information extracted than otherwise.

**Comment by sei-eschwartz** [comment]
Nothing too concerning, especially for a program of that size

**Comment by Detectronic-PB** [comment]
After a few adjustments to memory and swap on the container I'm now getting:

'''
Fail-Retracting factNOTConstructor(0x4f7de3)...
setting numGroup to 0x2 failed so setting to 1
Fail-Retracting guessedNOTConstructor(0x52b9d4)...
Fail-Retracting factNOTConstructor(0x52b9d4)...
tryBinarySearch completely failed on [0x52b9d4] and will now backtrack to fix an upstream problem.
guess: We have back-tracked to the call of tryBinarySearch(tryConstructor, tryNOTConstructor, [0x52b9d4, 0x4c96e7, 0x424cde, 0x415931, 0x536cb0, 0x5357ff, 0x52d483, 0x52d050, 0x52867f, 0x52856d, 0x527ea9, 0x527ae7, 0x521244, 0x5142c3, 0x50813f, 0x502989, 0x4f8465, 0x4dcf68, 0x4d193e, 0x4cfe49, 0x4ccd22, 0x4ca61a, 0x4bfb3e, 0x4aa46f, 0x4a9fc1, 0x4a7719, 0x4a0e6c, 0x499ec9, 0x471a5b, 0x45786b, 0x43cf62, 0x43a0a2, 0x4302d3, 0x425e15, 0x425d6d, 0x4153f0, 0x41467c, 0x4133ec, 0x4133c5])
Refusing to backtrack into reasoningLoop to fix an upstream problem because backtrackForUpstream/0 is not set.
'''

Full log: [prolog.zip](https://github.com/user-attachments/files/17962395/prolog.zip)

**Comment by sei-eschwartz** [comment]
This is pretty unusual.  Most times it happens it is a problem with fact generation.  I'll try to look on Monday.

**Comment by edmcman** [comment]
From a quick glance, it does look like a constructor to me.

**Comment by edmcman** [comment]
```
Guessing factConstructor(0x52b9d4).
Contradictory information about constructor: factConstructor(0x426738) but reasonNOTConstructor(0x426738)
Guessing factNOTConstructor(0x52b9d4).
Contradictory information about constructor: factConstructor(0x426738) but reasonNOTConstructor(0x426738)
```

So no matter what guess we make about 0x52b9d4, we decide that 0x426738 is both a constructor and not a constructor.

0x52b9d4 is probably CScrollView::CScrollView.  0x426738 is probably CWnd::CWnd.  0x52b9d4 calls 0x4f7de3, which calls 0x426738.

`reasonNOTConstructor_F(0x426738, 0x4f7de3)` is why we are concluding about 0x426738...  0x4f7de3 is the intermediate function above.

NOTConstructor_F is:
> % Because it is called by a non-constructor on the same object instance.

So that makes sense if we guess that 0x52b9d4 is not a constructor.  What about when we guess it is a constructor?

`reasonNOTConstructor_G(0x52b9d4, 0x4f7de3)`

So there we decide that 0x4f7de3 is not a constructor because of _G, which is:
> % Because you can't be a constructor on a class that's already known to have a VFTable if you
> % you don't have a VFTable.  This rule was added largely to reach the correct conclusions on
> % methods like operator=.

Interesting.

**Comment by sei-eschwartz** [comment]
Oops, back to work persona.  I think I figured out what is going wrong with the help of https://github.com/edmcman/MFCApplication.

This confirms that CScrollView::CScrollView calls CView::View:

![image](https://github.com/user-attachments/assets/3384c8c0-1931-40f3-a065-b2bfb262fd47)

Now, surprisingly to me, CView::CView does not have a vftable installation:

![image](https://github.com/user-attachments/assets/dc60edbe-3b9c-4abb-bf90-4ce00464b77e)

This is at odds with `reasonNOTConstructor_G`.  Then after a little digging, I found that interface classes in ATL like CView use a special property called [novtable](https://learn.microsoft.com/en-us/cpp/cpp/novtable?view=msvc-170).

**Comment by sei-eschwartz** [comment]
What should we do about this?  In general, I'm not sure.  If I were you for the moment, I would hack reasonNOTConstructor_G so that it ignores the vftable for CScrollView.  

``` prolog
% Because you can't be a constructor on a class that's already known to have a VFTable if you
% you don't have a VFTable.  This rule was added largely to reach the correct conclusions on
% methods like operator=.
% ED_PAPER_INTERESTING
reasonNOTConstructor_G(Method) :-
    % There's another method that calls this method on the same object pointer.
    validMethodCallAtOffset(_, Caller, Method, 0),
    % The caller is known to be a constructor or destructor.
    (factConstructor(Caller); factRealDestructor(Caller)),
    % The caller is already known to have a VFTable write.
    factVFTableWrite(_Insn1, Caller, 0, VFTable1),
    % HACK: NOT CScrollView::vftable
    iso_dif(VFTable1, 0x58eb84),
    % But this method doesn't have the required write.
    not(possibleVFTableWrite(_Insn2, Method, _ThisPtr, 0, _VFTable2)),
    % Since we don't have visibility into VFTable writes from imported constructors and
    % destructors this rule does not apply to imported methods.
    not(symbolClass(Method, _, _, _)),
    % Debugging
    logtraceln('~@~Q.', [not(factNOTConstructor(Method)),
                         reasonNOTConstructor_G(Caller, Method)]).
```

**Comment by Detectronic-PB** [comment]
Judging by [the MSDN](https://learn.microsoft.com/en-us/cpp/mfc/reference/cscrollview-class?view=msvc-170) it seems that 0x4f7de3 is CView::CView.

This leads to the documented inheritance of CScrollView : CView : CWnd.

So _G seems to be at issue. What does "if you don't have a VFTable" actually mean in this context?

**Comment by Detectronic-PB** [comment]
Oops, the window hadn't updated. I'll do that hack and see if I can make progress.

**Comment by Detectronic-PB** [comment]
After a couple of false starts and a switch to a machine with more memory, it finally completed. There was one more mod needed to avoid tripping up reasonNOTConstructor_G again.

**Comment by sei-eschwartz** [comment]
Glad to hear it!  I'm going to close this since we created #276 to keep track of the more general problem.
