### ISSUE TITLE
Working with Ghidra. json

### ISSUE THREAD

**Issue by MagnificentS** [cmu-sei/pharos#28]
How do I use this tool on windows?
I built the ghidra plugin but i could do nothing else without the json file.

**Comment by sei-ccohen** [comment]
You need to run the OOAnalyzer tool to generate the JSON file.  This requires building the Pharos framework and the OOAnalyzer tool, then running them on a Linux (or Mac) system.  The OOAnalyzer tool has neveer been run on a Windows system to my knowledge, although it might be possible.

**Comment by MagnificentS** [comment]
Thanks. I guess I need a linux install
