### ISSUE TITLE
Ctrl+C

### ISSUE THREAD

**Issue by Trass3r** [cmu-sei/pharos#33]
Just a nice to have: catch the signal and proceed like the total time limit was hit so it still produces an output.

**Comment by sei-ccohen** [comment]
Catch which signal?  I thought we did this for cases where we can recover, or there's some expectation that the condition might actually occur.  For cases that are truly unexpected, the signal is probably an alternative to dumping core.  Can you provide a log or the message you're referring to?

**Comment by sei-ccohen** [comment]
We've implemented something better for Ctrl-C handling now.  Please take a look at the latest commit and let us know if it addressed your concern.   We're still working on getting it to do something more useful during Prolog analysis, and it hasn't been tested well, but it's an improvement.   Please close the issue if you agree, or feel free to comment here on the change.

**Comment by sei-eschwartz** [comment]
Please reopen if this is still an issue.
