### ISSUE TITLE
build_prereqs.bash git clone z3 typo

### ISSUE THREAD

**Issue by Todd-Fulton** [cmu-sei/pharos#54]
In the build_prereqs.bash script there is a small typo
`git clone --depth 1 -b Z3-4.8.6 https://github.com/Z3Prover/z3.git z3`

should be

`git clone --depth 1 -b z3-4.8.6 https://github.com/Z3Prover/z3.git z3`

the capital Z results in an error.

`warning: Could not find remote branch Z3-4.8.6 to clone.
fatal: Remote branch Z3-4.8.6 not found in upstream origin`

thx

**Comment by sei-ccohen** [comment]
@sei_eschwartz also spotted this a couple of hours ago and fixed it.  The bug was introduced by me because I forgot that Z3 had been inconsistent with the name of their tag in the previous release.  Thanks for reporting the issue though!
