### ISSUE TITLE
Support for Linux 64 bit ELF files

### ISSUE THREAD

**Issue by KevinPoole** [cmu-sei/pharos#57]
From scanning through other issues it seems this may be something that is being actively worked. This would be a wonderful feature. Any chance there is a ball park estimate for when this feature would be added? I refer particularly to the OOanalyzer tool.

**Comment by sei-ccohen** [comment]
Linux 64-bit ELF files are receiving some attention, but it's mostly from an external collaborator, so I can't offer any estimates or make any commitments.  Some experiments on Linux x64 have yielded encouraging results, while others have indicated that there's a lot of work yet to be done.  A lot of the issues are related to calling convention differences and compiler design choices for internal implementation features like virtual function table layout (which will require some new rules).

**Comment by KevinPoole** [comment]
Ah, understood. Well, a cool tool nonetheless. Thanks for the quick reply!
