### ISSUE TITLE
Plugin not working ghidra version 9.1.1

### ISSUE THREAD

**Issue by madirishman0306** [cmu-sei/pharos#59]
Hey,

I have compiled the OOAnalyzer plugin successfully for ghidra, imported the plugin but it seems that ghidra doesn't recognize the plugin so the CERT dropdown is not available.

Any guidelines?
![issue1](https://user-images.githubusercontent.com/60310162/73131706-c7945000-4018-11ea-8882-f976ed9a26a0.png)
![issue2](https://user-images.githubusercontent.com/60310162/73131707-c82ce680-4018-11ea-81ec-b494c0c39402.png)

Regards!

**Comment by jeffgennari** [comment]
Hello,

Have you tried installing the plugin via Ghidra's "Install Extension" procedure? That is the typical way that we load new plugins.
