### ISSUE TITLE
OOAnalyzer reports DLL built by Visual C++ 6.0 contains no classes

### ISSUE THREAD

**Issue by holmesmr** [cmu-sei/pharos#61]
I'm attempting to analyze a DLL I know to have been written in C++ and compiled by Visual C++ 6.0 (is this supported?), but OOAnalyzer reports that it doesn't contain any classes at all (disproven by basic examination in Ghidra, as well as a copy of the linker mapfile).

Output from analysis as below:
```
OPTI[INFO ]: Analyzing executable: engine-netbabel.dll
OPTI[INFO ]: OOAnalyzer version 1.0.
OPTI[INFO ]: ROSE stock partitioning took 70.525 seconds.
OPTI[INFO ]: Partitioned 187777 bytes, 67592 instructions, 15381 basic blocks, 3 data blocks and 1092 functions.
OPTI[INFO ]: Pharos function partitioning took 93.7035 seconds.
OPTI[INFO ]: Partitioned 212992 bytes, 71498 instructions, 17081 basic blocks, 1112 data blocks and 2492 functions.
[INFO ]: Function 0x10005080 has no out edges.
OOAN[ERROR]: Found only 2266 functions of 2268 specifically requested for analysis.
OPTI[INFO ]: Function analysis complete, analyzed 2266 functions in 61.6782 seconds.
PLOG[FATAL]: No complete solution was found!
OPTI[ERROR]: No C++ classes were detected in the program.
OPTI[INFO ]: Successfully exported to JSON file 'engine-netbabel.json'.
OPTI[INFO ]: OOAnalyzer analysis complete.
```

It's a release binary, with no embedded debugging info (and obviously it's an x86 Win32 binary).

**Comment by sei-eschwartz** [comment]
Hmm, that is odd.  It looks like Prolog may have failed.  Can you share the .facts file?

**Comment by holmesmr** [comment]
Here's output from a run where I enabled Prolog facts/results output:
```
OPTI[INFO ]: Analyzing executable: engine-netbabel.dll
OPTI[INFO ]: OOAnalyzer version 1.0.
OPTI[INFO ]: ROSE stock partitioning took 71.0342 seconds.
OPTI[INFO ]: Partitioned 187777 bytes, 67592 instructions, 15381 basic blocks, 3 data blocks and 1092 functions.
OPTI[INFO ]: Pharos function partitioning took 94.2604 seconds.
OPTI[INFO ]: Partitioned 212992 bytes, 71498 instructions, 17081 basic blocks, 1112 data blocks and 2492 functions.
[INFO ]: Function 0x10005080 has no out edges.
OOAN[ERROR]: Found only 2263 functions of 2268 specifically requested for analysis.
OPTI[INFO ]: Function analysis complete, analyzed 2263 functions in 61.023 seconds.
PLOG[FATAL]: No complete solution was found!
OPTI[ERROR]: No C++ classes were detected in the program.
OPTI[INFO ]: OOAnalyzer analysis complete.
```
And the actual `.facts` file outputted (renamed to .txt so GH issues upload will accept it)
[ooa-engine-netbabel.facts](https://github.com/cmu-sei/pharos/files/4160744/ooa-engine-netbabel.facts.txt)

**Comment by sei-eschwartz** [comment]
```
Concluding mergeClasses(0x10035154, 0x10035164).
Merging class 0x10035164 into 0x10035154 ...
Retracting trigger_fact(factClassSizeGTE(0x10035164, 0)) and asserting trigger_fact(factClassSizeGTE(0x10035154, 0)) ...
Retracting factClassSizeGTE(0x10035164, 0) and asserting factClassSizeGTE(0x10035154, 0) ...
reasonForwardAsManyTimesAsPossible
Consistency checks failed.
A class may not have more than one real destructor:
 Class=0x10035154 Dtor1=0x10035164 Dtor2=0x10035154
Failed sanity check during forward reasoning
```

So the problem is that during the initial forward reasoning process, before any guesses have been made, we make a bad conclusion.  Because there are no guesses, there is nothing to backtrack into, and we just give up.

So we need to figure out why the reasoning rules decided to (wrongly) try to merge those two classes.

This sounds like a job for @sei-ccohen!  Can you take a look at this?  I'll attach the full log.

**Comment by sei-eschwartz** [comment]
[log.txt](https://github.com/cmu-sei/pharos/files/4165685/log.txt)

**Comment by sei-eschwartz** [comment]
[log.txt](https://github.com/cmu-sei/pharos/files/4165720/log.txt)
Here is an updated log with some more debug output.  Interestingly:

`reasonMergeClasses_G(0x10035154, 0x10035164, std::basic_ostringstream<char, struct std::char_traits<char>, class std::allocator<char> >, 0x10035154, 0x10035164).`

which means that the class merger is coming from import symbols.  So that is probably correct.  So our reasoning about the real destructors must be incorrect.

**Comment by sei-eschwartz** [comment]
It gets weirder.  Both of the real destructors also come from symbols.

**Comment by sei-eschwartz** [comment]
Both destructors come from https://github.com/cmu-sei/pharos/blob/2ff59e71b59725742ab9c53a77ba49316e6fe44e/share/prolog/oorules/rules.P#L351

I'm not sure what a vbase destructor is (haven't looked much yet), but apparently they are not the same as a real destructor, and there can be multiple of them.

**Comment by sei-eschwartz** [comment]
@holesmr For now as a work-around, you can comment out this rule: https://github.com/cmu-sei/pharos/blob/2ff59e71b59725742ab9c53a77ba49316e6fe44e/share/prolog/oorules/rules.P#L351

**Comment by holmesmr** [comment]
I'll give this a go later and see how it turns out.

**Comment by sei-eschwartz** [comment]
Here's what I got: 
[final.txt](https://github.com/cmu-sei/pharos/files/4165916/final.txt)

**Comment by sei-ccohen** [comment]
> There can be both a regular destructor and a vbase destructor apparently...

Huh.  I'm pretty sure that we have a rule that says that there can only be one real destructor per class.  Apparently that's incorrect.  It's always fun to learn something new about the compilers. :-)  We can discuss in person and try to correct the rule.  In the meantime, I agree the disabling the broken rule is the correct workaround.

**Comment by sei-eschwartz** [comment]
@sei-ccohen We never decided on a course of action here.  I am going to disable this rule in our next update.  #75 is a more open ended issue for how we should handle vbase destructors in general.

**Comment by sei-eschwartz** [comment]
This rule is disabled, though we still need a more complete fix
