### ISSUE TITLE
CPU not full usage

### ISSUE THREAD

**Issue by happydpc** [cmu-sei/pharos#63]
I am running a analysis on a dll about 25Mb, with threads 16, but the cpu usage is about 15%, that's too low and cost too much time. How can I fully use the cpu compute capabilities?

**Comment by sei-eschwartz** [comment]
Not all of Pharos can be run in parallel.  What tool are you using, and what does the log indicate is going on at that time?

**Comment by happydpc** [comment]
I am using ooanalyze, the partion step may const too much time and not utilize full cpu cores. And now the prolog reasoning step conitnues log  "update_return_values, no output state for xxxxxx". Can I ignore these errors log?

**Comment by happydpc** [comment]
Because the partioning step is so slow, I have to run serval binaries together to reduce the whole time. 

![image](https://user-images.githubusercontent.com/771776/75566910-8cf45c00-5a8b-11ea-9b09-5dddf1af8252.png)

**Comment by sei-eschwartz** [comment]
To speed up partitioning, you can try using `--no-semantics`.

If you are seeing a lot of errors about no output state, you have probably run into a resource limit.  Try the following options: `--timeout 86400 --maximum-memory 100000 --partitioner-timeout 86400`

**Comment by happydpc** [comment]
Ok, thank you, I will hava a try.

**Comment by happydpc** [comment]
> To speed up partitioning, you can try using `--no-semantics`.
> 
> If you are seeing a lot of errors about no output state, you have probably run into a resource limit. Try the following options: `--timeout 86400 --maximum-memory 100000 --partitioner-timeout 86400`

Can I just run some analysis on specific class or symbol, because I can figure the address manually or from the export table symbol, I can figure out some class. How to just run some of them, not all ? 
Analysing whole binary cost too much time.

**Comment by sei-eschwartz** [comment]
This is not really possible in OOAnalyzer.  Even if you know which methods you are interested in, facts from other methods still play an important role in deducing information.

**Comment by sei-eschwartz** [comment]
If you are still having trouble, please reopen.
