### ISSUE TITLE
OOAnalyzer Ghidra plugin creates anonymous class instead of using existing class

### ISSUE THREAD

**Issue by happydpc** [cmu-sei/pharos#66]
As the image shows, this is a constructor, the signature is given by the symbol. But after using ooanalyzer, it creates an anonymous class, and that's unnecessary. Although this is a base class, it should use itself, not create a new anonymous class. 
![image](https://user-images.githubusercontent.com/771776/75598575-9f948280-5ad7-11ea-937f-f23cf07865e7.png)

**Comment by sei-eschwartz** [comment]
@sei-jgennari Were you able to look at this?

**Comment by jeffgennari** [comment]
@sei-eschwartz I will take a look

**Comment by sei-eschwartz** [comment]
@happydpc can you see if this is still a problem?  We've overhauled a lot of this logic.

**Comment by sei-eschwartz** [comment]
Please reopen if it's still a problem.
