### ISSUE TITLE
OOAnalyzer does not support ARMV5TLE binaries

### ISSUE THREAD

**Issue by martmists** [cmu-sei/pharos#69]
It simply logs 
```
root@ee5411403779:/# ooanalyzer /dir/arm9.bin --json /dir/data.json
OPTI[INFO ]: Analyzing executable: /dir/arm9.bin
OPTI[INFO ]: OOAnalyzer version 1.0.
OOAN[FATAL]: Pharos main error: unrecognized file format for "/dir/arm9.bin": data
```

**Comment by sei-eschwartz** [comment]
ROSE does not have ARM semantics, so this is unlikely to happen anytime soon.  We are investigating the possibility of exporting facts from Ghidra and/or angr, but this is just an idea at the moment.

**Comment by sei-eschwartz** [comment]
Closing since this won't realistically be fixed anytime soon.
