### ISSUE TITLE
apianalyzer all api sequences

### ISSUE THREAD

**Issue by jhong3842** [cmu-sei/pharos#7]
Can not you extract the entire sequence of api that runs as the program runs in apianalyzer? Without exactly defined api signature

**Comment by jeffgennari** [comment]
You can certainly use an off-the-shelf API tracer to gather the sequence of API calls made by an executable, although this is tricky in a static analysis context. However, this is not the goal of ApiAnalyzer; rather, the tool is designed to find known sequences of API function calls. The premise being that these sequences represent behaviors of interest. Discovery of sequences is a slightly different concern.

**Comment by jeffgennari** [comment]
Actually, there is a utility named apigraphgen included in the repository that will emit the API call graphs foreach function in a program. Perhaps this can help you?

**Comment by jhong3842** [comment]
Thank you. There was a lot of help.
