### ISSUE TITLE
ooanalyzer fails due to missing path

### ISSUE THREAD

**Issue by rokups** [cmu-sei/pharos#72]
After a long while (presumably at the end of analysis) ooanalyzer starts spamming following errors:
```
OPTI[FATAL]: Unable to start Prolog session.
OPTI[FATAL]: Cannot generate a new XSB session until current one is destroyed.
OPTI[ERROR]: Error cannot start prolog
OPTI[FATAL]: Unable to start Prolog session.
OPTI[FATAL]: Unable to start Prolog session.
OPTI[FATAL]: Cannot generate a new XSB session until current one is destroyed.
OPTI[FATAL]: XSB Error: existence_error/++Error[XSB/Runtime/P]: [Existence (No file/module /usr/local/share/pharos/prolog/types/typerules exists)]  in arg 1 of predicate /(consult,1)
OPTI[ERROR]: Error cannot start prolog
OPTI[ERROR]: Error cannot start prolog
OPTI[FATAL]: Unable to start Prolog session.
OPTI[FATAL]: Cannot generate a new XSB session until current one is destroyed.
OPTI[ERROR]: Error cannot start prolog
OPTI[FATAL]: Unable to start Prolog session.
OPTI[FATAL]: XSB Error: existence_error/++Error[XSB/Runtime/P]: [Existence (No file/module /usr/local/share/pharos/prolog/types/typerules exists)]  in arg 1 of predicate /(consult,1)
OPTI[FATAL]: Unable to start Prolog session.
OPTI[FATAL]: Cannot generate a new XSB session until current one is destroyed.
```
Tested with latest docker image.

**Comment by sei-eschwartz** [comment]
I just tested this and wasn't able to reproduce the problem.

What command line were you running?  What binary (if you can share it)?  And what is the sha256 of the docker image you are using?

**Comment by rokups** [comment]
Image hash: sha256:0a696c219dc8e6f2351cf4142b251ceaa1a016e2ebd54c3855d3390a54aed262
Unfortunately i am unable to share binary. However i can tell that it is 9+MB 32bit standard executable built in debug mode, no fancy protections or anti-analysis tricks.

> What command line were you running?

Used flags: `--timeout=0 --partitioner-timeout=0 --maximum-memory=0 --threads=24 --analyze-types -j executable.exe.json -f ./executable.exe`.

This is what i get in a fresh docker container:
```
root@2433ecf121b2:/# ls /usr/local/share/pharos/prolog/types/typerules
ls: cannot access '/usr/local/share/pharos/prolog/types/typerules': No such file or directory
```
Container is started as per example in readme: `docker run --rm -it -v `pwd`:/user seipharos/pharos`.

**Comment by edmcman** [comment]
Ah, don't use `--analyze-types`.  That doesn't effect OOAnalyzer at all and should probably be removed.

**Comment by rokups** [comment]
Opss. Thank you :+1:

**Comment by sei-eschwartz** [comment]
Thanks for the report.  Let us know how it goes without `--analyze-types`.

Also, with an executable of that size, you will probably be better off using SWI prolog.  @sei-ccohen described this a bit [here](https://github.com/cmu-sei/pharos/issues/71#issuecomment-613657163) but it's not well documented.  Let us know if you run into any trouble.
