### ISSUE TITLE
How can I extend the API database?

### ISSUE THREAD

**Issue by janbbeck** [cmu-sei/pharos#74]
Hi, I got a warning:
`APID[WARN ]: API database has no data for DLL: MFC42`

So my question is how I would add data for that? Is it as simple as using ooanalyzer on that dll and grabbing the json and putting it somewhere? Some other way of integrating perhaps publicly available information on MFC?

Thanks in advance,

Jan

**Comment by sei-eschwartz** [comment]
So for small non-standard DLLs you can add data to the API database by putting it in `share/apidb/pharos-api-additions.json`.  This is not the same json that ooanalyzer outputs.  We don't have a public tool to assist with this.

The idea behind the default APIDB is that it should cover "standard" DLLs.  We built it by scraping sources like MSDN.  I'm not sure why that wouldn't have included MFC42.  @sei-ccohen @sei-mwd  know more about the API database.  Can we possibly add MFC42?

**Comment by sei-ccohen** [comment]
I agree that manually adding entries to the pharos-api-additions.json is the appropriate solution.   It's also important to know that it's much more important to have the correct _number_ of arguments than it is to have the correct types, names, etc.   Those fields are primarily for future Pharos improvements.  The important problem that the API database is really addressing in OOAnalyzer is determining the overall stack delta change of 32-bit __stdcall APIs in Windows.   without knowing the number of parameters, it's difficult to know how many bytes the call pops off the stack, and without knowing that it's very difficult to analyze functions that contain such calls correctly.  So if listing the individual parameters is a nuisance, you can try specifying "delta": "16" for a four parameter function for example.

The reason that we haven't generated an automatically scraped API database for MFC is that unlike most other common DLLs, MFC is heavily object oriented, and to do a proper job of the generating the API database will require a lot more effort than for other non-object oriented DLLs.  It also feels like something more intelligent should be done for OOAnalyzer, but that's not required to improve the OOAnalyzer results (just some stack deltas).

**Comment by janbbeck** [comment]
Thank you for that reply!
With respect to the number of arguments, would this work:
- grab mfc42.def file with all the function names and arguments mangled
- use demangler to determine the number of parameters
- output to json file
?

**Comment by janbbeck** [comment]
Also, like this:?
```
{ "config": { "exports": [
{
  "dll": "MFC42.DLL",
  "export_name": "?GetButtonText@CToolBar@@QBE?AVCString@@H@Z",
  "display_name": "CToolBar::GetButtonText",
  "convention": "thiscall",
  "parameters": [
     {"delta": "4"}
  ],
  "type": "CString",
  "ordinal": 2922
}
]}}

```

**Comment by cfcohen** [comment]
Exactly, except that "delta" is at the same level as "parameter".   Our sample API configuration file doesn't include the "delta" parameter, because you should specify it OR the parameter list with names and types.   You can test that your configuration is working by executing:

./tools/apilookup/apilookup '?GetButtonText@CToolBar@@QBE?AVCString@@H@Z'

Once you've created the first entry in the API configuration file for a given DLL, OOAnalyzer should complain about the individual missing functions.  Please let us know if you have any trouble getting it working.

**Comment by sei-mwd** [comment]
According to the API DB design, you should not have to add C++ mangled symbols in order to get useful stack delta information.  While looking into this I have found a small bug in the apilookup program, but I am surprised that you are getting the warning you are currently getting.  For example:

    $ tools/apilookup/apilookup 'MFC42.DLL:?GetButtonText@CToolBar@@QBE?AVCString@@H@Z'
    Lookup: MFC42.DLL:?GetButtonText@CToolBar@@QBE?AVCString@@H@Z
      Definition found
        Name: public: near class CString __thiscall CToolBar::GetButtonText(int) const 
        Export: ?GetButtonText@CToolBar@@QBE?AVCString@@H@Z
        DLL: mfc42
        Calling convention: thiscall
        Return_type: class CString
        Parameters: int
        Stack delta: 4
        Source: Decorated name parser

The bug I found is that the decorated name parser does not properly handle queries that don't have an attached DLL name.  I'm fixing that in our local sources.  But I'm curious how you got the mentioned warning.

**Comment by sei-mwd** [comment]
Here's another example that outputs a warning.  Could it be that it's not finding one instance but is working fine for others?  

    $ tools/apilookup/apilookup 'MFC42.DLL:foobar' 'MFC42.DLL:?GetButtonText@CToolBar@@QBE?AVCString@@H@Z'
    APID[WARN ]: API database has no data for DLL: mfc42
    Lookup: MFC42.DLL:foobar
      No definition found
    Lookup: MFC42.DLL:?GetButtonText@CToolBar@@QBE?AVCString@@H@Z
      Definition found
        Name: public: near class CString __thiscall CToolBar::GetButtonText(int) const 
        Export: ?GetButtonText@CToolBar@@QBE?AVCString@@H@Z
        DLL: mfc42
        Calling convention: thiscall
        Return_type: class CString
        Parameters: int
        Stack delta: 4
        Source: Decorated name parser

The warning is correct: there is no specific information for MFC42.DLL.  But it can still get information for symbols that pharos can properly demangle.  Try running your tests with the folloring argument: `--log=APID(all)'.  This will spew messages about how pharos looks up symbol information.  You may be find that there's only a few symbols that need to be added.

**Comment by janbbeck** [comment]
Thank you. That is very helpful. Especially the  --log option.


> Here's another example that outputs a warning. Could it be that it's not finding one instance but is working fine for others?
> 
> ```
> $ tools/apilookup/apilookup 'MFC42.DLL:foobar' 'MFC42.DLL:?GetButtonText@CToolBar@@QBE?AVCString@@H@Z'
> APID[WARN ]: API database has no data for DLL: mfc42
> Lookup: MFC42.DLL:foobar
>   No definition found
> Lookup: MFC42.DLL:?GetButtonText@CToolBar@@QBE?AVCString@@H@Z
>   Definition found
>     Name: public: near class CString __thiscall CToolBar::GetButtonText(int) const 
>     Export: ?GetButtonText@CToolBar@@QBE?AVCString@@H@Z
>     DLL: mfc42
>     Calling convention: thiscall
>     Return_type: class CString
>     Parameters: int
>     Stack delta: 4
>     Source: Decorated name parser
> ```
> 
> The warning is correct: there is no specific information for MFC42.DLL. But it can still get information for symbols that pharos can properly demangle. Try running your tests with the following argument: `--log='APID(all)'`. This will spew messages about how pharos looks up symbol information. You may find that there's only a few symbols that need to be added.

**Comment by janbbeck** [comment]
Using the `--log` parameter, I still get MFC related failure messages

```
API Lookup: MFC42:4441
APID[WHERE]: JSON API database /usr/local/share/pharos/apidb/pharos-api-additions.json has no data for DLL: MFC42
APID[WHERE]: SQLite API database /usr/local/share/pharos/apidb/pharos-apidb.sqlite has no data for DLL: MFC42
APID[WHERE]: Decorated name parser has no data for DLL: MFC42
APID[WARN ]: API database has no data for DLL: MFC42
APID[TRACE]: API Lookup: MFC42:2648
APID[TRACE]: API Lookup: MFC42:2055
APID[TRACE]: API Lookup: MFC42:6376
APID[TRACE]: API Lookup: MFC42:3749
```
.. and so on.

**Comment by sei-mwd** [comment]
> If I use the json mechanism discussed above to add them, will that connect these ordinals to the correct function names?

Yes.  That's the missing bit of information: that it was looking things up by ordinal.  That needs an existing mapping, and the json mechanism is the easiest way for you to supply that.

**Comment by sei-mwd** [comment]
Just had a thought that could simplify your creation of the db.  You can use the `apilookup` to create json templates from the mangled names that you can fill in with the ordinal information.  For example:

    $ apilookup --pretty=4 --json=-  'mfc42.dll:?GetButtonText@CToolBar@@QBE?AVCString@@H@Z'
    [
        {
            "convention": "thiscall",
            "display_name": "public: near class CString __thiscall CToolBar::GetButtonText(int) const ",
            "dll": "mfc42",
            "export_name": "?GetButtonText@CToolBar@@QBE?AVCString@@H@Z",
            "parameters": [
                {
                    "type": "int"
                }
            ],
            "source": "Decorated name parser",
            "type": "class CString"
        }
    ]

**Comment by janbbeck** [comment]
> Just had a thought that could simplify your creation of the db. You can use the `apilookup` to create json templates from the mangled names that you can fill in with the ordinal information. For example:
> 
> ```
> $ apilookup --pretty=4 --json=-  'mfc42.dll:?GetButtonText@CToolBar@@QBE?AVCString@@H@Z'
> [
>     {
>         "convention": "thiscall",
>         "display_name": "public: near class CString __thiscall CToolBar::GetButtonText(int) const ",
>         "dll": "mfc42",
>         "export_name": "?GetButtonText@CToolBar@@QBE?AVCString@@H@Z",
>         "parameters": [
>             {
>                 "type": "int"
>             }
>         ],
>         "source": "Decorated name parser",
>         "type": "class CString"
>     }
> ]
> ```

good idea! I think that is just what I will do. My manually constructed test case worked, btw:
```
APID[TRACE]: API Lookup: MFC42:4441
APID[TRACE]: JSON API database /usr/local/share/pharos/apidb/pharos-api-additions.json found ordinal 4441 for MFC42
APID[DEBUG]: mfc42|||?OnCommand@CWnd@@MAEHIJ@Z|CWnd::OnCommand|4441||thiscall|CString|8|()
```
does it have to be the 'pharos-api-additions.json' file, or will any json file in that directory be used?

Also, does ooanalyzer know what CWnd and CString are btw? Can I tell it? Does it matter? :P

**Comment by sei-ccohen** [comment]
Pharos supports a configuration file.   You can run "ooanalyzer --dump-config" to dump the current configuration in the correct YAML format.   The resulting file can be placed in ~/.yaml.config and edited to change the list of files in the apidb list.

As for types, OOAnalyzer doesn't really make much use of the actual types right now (the deltas being what's most important).   But there is a typedb parameter listed in the configuration, with another JSON file that defines the types recognized in the APIDB.  The format is hopefully obvious enough that you'll be able to muddle through, but if you have questions, feel free to ask.

**Comment by janbbeck** [comment]
Ok, I have made a `pharos-api-additions.json` file with mfc42 coverage. Are you guys interested in some sort of PR for that?

Thanks for all the help

**Comment by janbbeck** [comment]
I am getting a lot of these kinds of errors:
```
OOAN[ERROR]: Missing return value from new() call at 0x0069F1C0
OOAN[ERROR]: Missing return value from new() call at 0x0069F2C9
```
Should I be concerned?

**Comment by sei-eschwartz** [comment]
Maybe post the json file here and we'll take a look?  I think that we can't include anything with ordinals, but @sei-ccohen can comment more on that.

The missing return value is odd... usually we see these when we've hit a resource limit, but we disabled most of these in the last release.  How many are you seeing?

**Comment by janbbeck** [comment]
> Maybe post the json file here and we'll take a look? I think that we can't include anything with ordinals, but @sei-ccohen can comment more on that.
> 
> The missing return value is odd... usually we see these when we've hit a resource limit, but we disabled most of these in the last release. How many are you seeing?

Sure, see attached.
Why would the ordinals be a problem?
[mfc42pretty.zip](https://github.com/cmu-sei/pharos/files/4569617/mfc42pretty.zip)

**Comment by sei-eschwartz** [comment]
I believe in some DLLs the ordinals would change in each version of the DLL.  Maybe this isn't true of user facing DLLs like MFC?  @sei-ccohen or @sei-mwd will know more.

**Comment by sei-mwd** [comment]
It is my belief that ordinals are declared by Microsoft to be consistent within MFCxx.DLL for any specific xx.

**Comment by sei-ccohen** [comment]
MFC is an unusual case because they exclude the export names from the file and rely on ordinals.   While I think @sei-eschwartz may be right in general, I think @sei-mwd may be correct for MFCxx.DLL.  If he is we should definitely consider incorporating @janbbeck's updates into our database, although we'll probably want to merge it with the SQLLite database and not the JSON file.

**Comment by janbbeck** [comment]
I think that is true. They create a new ordinal for a new version of the DLL. Consider the mfc42.def file included in visual studio:

```
; MFC 4.2(final release)
 ??0_AFX_CHECKLIST_STATE@@QAE@XZ @ 256 NONAME
 ??0_AFX_COLOR_STATE@@QAE@XZ @ 257 NONAME
 ??0_AFX_CONTROLPOS@@QAE@XZ=_AfxBinaryCompatibleStubFunction @ 258 NONAME
 ??0_AFX_DAO_STATE@@QAE@XZ @ 259 NONAME
 ??0_AFX_EDIT_STATE@@QAE@XZ @ 260 NONAME
 ??0_AFX_OLE_STATE@@QAE@XZ @ 261 NONAME
 ??0_AFX_THREAD_STATE@@QAE@XZ @ 262 NONAME
 ??0_AFX_WIN_STATE@@QAE@XZ @ 263 NONAME
 ??0_AFXCTL_AMBIENT_CACHE@@QAE@XZ @ 264 NONAME
 ??0_AFXCTL_UIACTIVE_INFO@@QAE@PAUHMENU__@@PAUIOleInPlaceFrame@@@Z @ 265 NONAME
 ??0AFX_CLASSINIT@@QAE@PAUCRuntimeClass@@@Z=??0AFX_CLASSINIT_COMPAT@@QAE@PAUCRuntimeClass@@@Z @ 266 NONAME
```
notice the equal sign for the mangled name for ordinal 266. Then further down:

```
; MFC 6.0 (Beta 2 Release)
;
 ??0AFX_CLASSINIT_COMPAT@@QAE@PAUCRuntimeClass@@@Z @ 6465 NONAME
```
and there is also
```
; MFC 4.21(final release)
 ??0CEnumConnections@@QAE@PBXI@Z @ 6428 NONAME
 ??1CEnumConnections@@UAE@XZ @ 6429 NONAME
```

so it really looks they do version management by appending new ordinals.

**Comment by sei-eschwartz** [comment]
Closing this in favor of the more general #108
