### ISSUE TITLE
Improve installation/build instructions for OOAnalyzer Ghidra Plugin or provide pre-built plugin

### ISSUE THREAD

**Issue by tfriesen** [cmu-sei/pharos#76]
The scant instructions provided in the README for the OOAnalyzer Ghidra plugin do not enable a user to successfully build or install the plugin.

For example, the instructions say to install the plugin using the 'standard procedure'. Well, the standard procedure is to point Ghidra at a zip file containing the extension... except there is no zip file, nor are there any instructions for generating one.

The plugin can be manually built using gradle, once the user figures out how to deal with the unmentioned dependency on junit, but we still don't have a zip file. Zipping up the resulting directories in a manner similar to other Ghidra plugin produces an extension that won't install unless the extensions.properties is manually clobbered with proper values. And while the result will install, trying to run the script fails with errors about not being able to find 'ooanalyzer' package.

**Comment by jeffgennari** [comment]
The OOAnalyzer plugin is a standard Ghidra plugin. See the release notes included with Ghidra:

https://ghidra-sre.org/InstallationGuide.html#GhidraExtensionNotes

I suggest building the extension with the GhidraDev plugin - it simplifies finding the dependencies

**Comment by sei-eschwartz** [comment]
@tfriesen Did you try `gradle buildExtension`?

**Comment by sei-eschwartz** [comment]
@sei-ccohen @sei-jgennari @sei-mwd Should we have a binary release of the plugin?

**Comment by sei-eschwartz** [comment]
@tfriesen Thanks for the feedback.  I'm going to be looking at improving our docs.  Just to be clear, were you ever able to get the built plugin working?

**Comment by tfriesen** [comment]
@jeffgennari Yes, I read those docs very thoroughly; they are also quite scant on detail.

@sei-eschwartz Yes! `gradle buildExtension` was the magic command I needed, thank-you. Notably, that is not one of the options listed when `gradle tasks` is run.

**Comment by sei-eschwartz** [comment]
I'm glad that helps.  What Ghidra version are you using?  I just tried this morning with Ghidra 9.1.2 and I actually didn't need to specify any argument.

**Comment by jeffgennari** [comment]
The dependency on junit is a mistake. The tests for OOAnalyzer were inadvertently uncommented. This has been addressed in the latest commit

**Comment by janbbeck** [comment]
> 
> 
> I'm glad that helps. What Ghidra version are you using? I just tried this morning with Ghidra 9.1.2 and I actually didn't need to specify any argument to gradle.

I also just finished building for 9.1.2 using gradle 6.3 on Ubuntu 20.04. Did not have specify argument either

**Comment by sei-eschwartz** [comment]
@tfriesen We improved the documentation and added binary builds.  Let us know what you think.

**Comment by janbbeck** [comment]
where? Nothing shows upon github for me....

**Comment by sei-eschwartz** [comment]
https://github.com/cmu-sei/pharos/tree/master/tools/ooanalyzer/ghidra/OOAnalyzerPlugin

**Comment by janbbeck** [comment]
Ah. got it. Thanks!

**Comment by janbbeck** [comment]
Where would I find `ghidra_9.2_DEV_20200507` :P

**Comment by sei-eschwartz** [comment]
Here?

https://github.com/sei-eschwartz/pharos/releases/tag/ghidra-master
