### ISSUE TITLE
Ghidra won't load json file

### ISSUE THREAD

**Issue by janbbeck** [cmu-sei/pharos#77]
I am trying to load the json file ooanalyzer generated into ghidra. I am presented with an error message caused by this line in the OOAExampleScript.java:

```
			if (optList.isEmpty()) {
				Msg.showError(this, null, "Error",  "Could not load JSON from " + jsonFile.getName());
```

how do I diagnose this?

**Comment by sei-eschwartz** [comment]
I haven't looked in detail yet, but is the JSON file empty?  Could you share it?

**Comment by janbbeck** [comment]
Not empty. Glad to share. Thanks for looking into this.
[V9.zip](https://github.com/cmu-sei/pharos/files/4564375/V9.zip)

**Comment by sei-eschwartz** [comment]
15MB!  Wow, definitely not empty.

**Comment by janbbeck** [comment]
nevermind. I think another tool created that json file from the same executable and I looked in the wrong directory.

Sorry for the noise!

**Comment by sei-eschwartz** [comment]
Great!  That's the easiest problem I'll solve all day :-)
