### ISSUE TITLE
How serious are these error messages?

### ISSUE THREAD

**Issue by janbbeck** [cmu-sei/pharos#85]
I get the following error messages in the analysis. Is this common, or did something go unexpectedly wrong?

```
OOAN[ERROR]: No new() methods were found.  Heap objects may not be detected.
OOAN[ERROR]: No delete() methods were found.  Object analysis may be impaired.
OPTI[INFO ]: Function analysis complete, analyzed 49805 functions in 34905.7 seconds.
```

**Comment by sei-eschwartz** [comment]
OOAnalyzer has a few hashes of ::new and ::delete, but they didn't match anything your file.  Results will improve if you identify them and use `--new-method` and `--delete-method`.

**Comment by sei-eschwartz** [comment]
Looks like 0x8431ac is a thunk to MFC42.dll::operator delete and 0x8431b2 is a thunk to MFC42.dll::operator new.  @sei-ccohen @sei-mwd Shouldn't we auto-detect thunks to imported new/delete?

**Comment by sei-eschwartz** [comment]
This appears to be tied to the API database problems for MFC42.  Can confirm that when using @gwasser's new database we do not get this warning.

**Comment by janbbeck** [comment]
FYI, I did not use the json file that translates the MFC42 ordinals for this run. I wanted to address these messages first, before I submit the error messages that occur when I make that change. If I remember correctly, these messages multiply instead of disappear, but I am going to run that right now and report back.

**Comment by sei-eschwartz** [comment]
I suspect it identifies the new and delete by mangled name, so if you aren't exporting those it won't help.  But you should be able to manually specify the two thunk addresses.

**Comment by cfcohen** [comment]
Based on the APIDB log using the new database, it appears that the new & delete detection problem is because they were imported by ordinal and not by name.  In other words, we should detect thunks to new and delete imports automatically -- when they're imported by _name_.   For anyone trying to get the best possible performance from OOAnalyzer, my advice is to use the --new-method and --delete-method to explicitly enumerate these important methods before running OOAnalyzer.  If that's difficult, I usually find it much easier after OOAnalyzer has been run once and has identified a number of constructors.

**Comment by gwasser** [comment]
To be clear, we're internally testing a new larger APIDB that contains more information (e.g., mfc42.dll). Hopefully this database will be included in a public release in the near future.

**Comment by janbbeck** [comment]
Thanks for all that information. I am currently running a test using --new-method and --delete-method.

**Comment by sei-ccohen** [comment]
I should also add that we have a number of hardcoded function hashes in Pharos right now that are used to detect statically linked new() and delete() implementaitons.  Those should really be loaded from a JSON config file, but that's a separate problem.  If we fail to detect a statically linked implementation of new() or delete() I encourage users to let us know.

Here's the procedure for generating the hashes, using tests/ooex_vs2010/Lite/ooex2 as an example:
```
fn2hash --include-func 0x4010d5 --include-func 0x40112f tests/ooex_vs2010/Lite/ooex2.exe 2>/dev/null | cut -d, -f 8
3D3F9E46688A1687E2AB372921A31394
9F377A6D9EDE41E4F1B43C475069EE28
```

Which produces the hashes [here](https://github.com/cmu-sei/pharos/blob/master/libpharos/ooanalyzer.cpp#L344) and [here](https://github.com/cmu-sei/pharos/blob/master/libpharos/ooanalyzer.cpp#L355).  It's not the most elegant thing in the world, but it mostly works.

**Comment by janbbeck** [comment]
I can confirm that  using --new-method and --delete-method solves this particular issue. Thanks for taking the time to give me all that info.
