### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by Henbar-hust** [cmu-sei/pharos#9]
I installed it using command "$ docker build -t pharos .",
 but it finally returned 
"The command '/bin/sh -c /root/pharos/scripts/build.bash -reclaim &&  rm -rf /root/pharos &&  cd /usr/local/lib &&  find /usr/local/lib | xargs file | grep 'current ar archive' | awk -F':' '{print $1}' | xargs strip' returned a non-zero code: 2"
my OS is ubuntu 16.04, and I have tried it for many times, the results is same :(
is that because I'm lake of some dependencies?

**Comment by edmcman** [comment]
Can you include more of the error?  Specifically, what command failed inside the build.bash script that caused the process to fail?

Building the docker image requires a fair amount of memory and disk space, and it can fail if you don't have enough.  You can try [this branch](https://github.com/edmcman/pharos) which should help if either of those is the problem.

**Comment by edmcman** [comment]
It looks like it can't find ROSE.  Does /usr/local/bin/rose-config exist?

**Comment by Henbar-hust** [comment]
Yes it is. I chmod 777 of the it, and it didn't work. 
It has anything to do with the cmake version?

**Comment by edmcman** [comment]
What does /usr/local/bin/rose-config -V output?

**Comment by edmcman** [comment]
It sounds like a problem with ROSE, not cmake.

**Comment by sei-ccohen** [comment]
If you've built and installed ROSE using cmake, there are known problems with the ROSE cmake configuration that will prevent Pharos from building.  The failure to install rose-config is but one of these problems, and we're working with the ROSE developers to correct the issues.  In the mean time, it's important to ensure that you've built ROSE with automake.   Hopefully this helps resolve your issue.

**Comment by Henbar-hust** [comment]
It looks like a ROSE problem, 
![image](https://user-images.githubusercontent.com/43718223/49851301-ab851d80-fe1b-11e8-94ef-110dbe5c5bf7.png)
The librose.so* do exits, but the error still occurred. 
![image](https://user-images.githubusercontent.com/43718223/49851499-382fdb80-fe1c-11e8-81be-f338139ce841.png)

**Comment by Henbar-hust** [comment]
I have finished the installation just now by creating a new virtual machine. I gave the  VM 12G memory and it takes about 4 hours to install, these time I didn't meet error. I guess that it at least  need 10G memory to accomplish the installation if you want to success at the first time .Thank god and all of you :-)
There is another issue is when I use ooanalyzer by docker to analysis an file , I meet a XSB error :
![image](https://user-images.githubusercontent.com/43718223/49871635-bb1f5900-fe51-11e8-87ab-3bdcc918f9a2.png)
it looks like a path during installation.

By the way, is it normal Unable to start Prolog session?  ?_?

**Comment by edmcman** [comment]
I will see if I can reproduce, but does the referenced file exist, and is it readable by you?

**Comment by edmcman** [comment]
I don't see this behavior.  This is using our Docker file?  Did you modify anything?  What command line are you running?

**Comment by sei-ccohen** [comment]
It is not normal to fail when starting the Prolog session.  I've encountered the xsb_configuration.P error on several occasions, but do not understand the cause.   It's something in the XSB installation procedure.  My experience has been that touching the missing file is often sufficient to work around the problem.

**Comment by cyruliu** [comment]
> I don't see this behavior. This is using our Docker file? Did you modify anything? What command line are you running?

Hi, I have the same error when I run `callanalyzer --analyze-type --allow-64bit fp-5`, how can I solve the problem? The `/root` is empty on my container. When I run `callanalyzer --show-symbolic` on my efl executable, it shows complete, but where can I see the analysis result? I didn't see any new output file.

**Comment by edmcman** [comment]
The `--analyze-type` option uses Prolog, which explains why if you did not have a working Prolog installation you would get that error.

I think the problem is that we are removing the original build directories in /root to save space for the Docker container.  I believe that is removing files that XSB Prolog needs.  I am investigating more.

**Comment by cyruliu** [comment]
> The `--analyze-type` option uses Prolog, which explains why if you did not have a working Prolog installation you would get that error.
> 
> I think the problem is that we are removing the original build directories in /root to save space for the Docker container. I believe that is removing files that XSB Prolog needs. I am investigating more.

Thank you for the response and taking your time for my issue! I want to confirm with you that, does `pharos` also works for linux binary? As I found `tests` in the repository are all windows executable, I run `callanalyzer --show-symbolic` over `ELF` binaries, it shows nothing, but gives all the function calls (and parameters) when I run it on windows executable which I grab from `tests`.
I'm not quite understand how `callanalyzer` gets all the function calls (along with its parameters) from binary (so far as I understand, the binary is for windows executable?), I didn't find any `main` function call among those output though.

**Comment by sei-ccohen** [comment]
The Pharos framework has primarily been tested and developed to analyze Windows binaries.  The underlying ROSE framework supports ELF executables, and much of that capability has carried forward automatically into Pharos.  Importantly for type analysis and the CallAnalyzer tool, the API database is not populated with the parameter types of Linux API calls, which will reduce the effectiveness of the tool.   Conceptually it should not be too difficult to extend the API database to include some Linux APIs, but there are also some deficiencies in the Pharos framework related to ELF import handling.   In summary, you are correct in noting that CallAnalyzer does not currently operate on ELF executables as well as on Windows executables.  If you're interested in investigating further, look at apidb.cpp, and the SQLite database in share/apidb for the answers to some your questions about external API type detection.

**Comment by cyruliu** [comment]
> The Pharos framework has primarily been tested and developed to analyze Windows binaries. The underlying ROSE framework supports ELF executables, and much of that capability has carried forward automatically into Pharos. Importantly for type analysis and the CallAnalyzer tool, the API database is not populated with the parameter types of Linux API calls, which will reduce the effectiveness of the tool. Conceptually it should not be too difficult to extend the API database to include some Linux APIs, but there are also some deficiencies in the Pharos framework related to ELF import handling. In summary, you are correct in noting that CallAnalyzer does not currently operate on ELF executables as well as on Windows executables. If you're interested in investigating further, look at apidb.cpp, and the SQLite database in share/apidb for the answers to some your questions about external API type detection.

I see, thank you for the response! I will look into it.
