### ISSUE TITLE
What causes OOAN[FATAL]: XSB Error: misc_error/++Error[XSB/Runtime/P]:

### ISSUE THREAD

**Issue by janbbeck** [cmu-sei/pharos#90]
So, my computers were not able to cope with ooanalyzers requirements and so I rented an instance from Amazon EC2. After a day or so, the following happened:
```
APID[DEBUG]: msvcrt|4EEAE390||??3@YAXPAX@Z|??3@YAXPAX@Z|||cdecl|void||(void *)
OOAN[ERROR]: Found only 49693 functions of 49805 specifically requested for analysis.
OPTI[INFO ]: Function analysis complete, analyzed 49693 functions in 6273 seconds.
Warning: In assert to trigger_fact/1, an index hash chain is very long; consider using asserta, multi or no index.
PLOG[ERROR]: OOAnalyzer has been running for over an hour in Prolog mode.  We have found that for, complex executables, SWI Prolog often outperforms XSB Prolog.  You may wish to dump the .facts file for your executable using the -F option of ooanalyzer, and then run the oodebugrun-swipl script in share/pharos/oorules of your build directory.  You will need to install swipl and ensure it is on your PATH.
OOAN[FATAL]: XSB Error: misc_error/++Error[XSB/Runtime/P]: [Miscellaneous] Aborting...
OOAN[ERROR]: Failed to import object oriented results into Pharos.
OPTI[ERROR]: No C++ classes were detected in the program.
OPTI[INFO ]: Successfully exported to JSON file 'V9.json'.
OPTI[INFO ]: OOAnalyzer analysis complete.
```

at that point it used about 110GB of memory out of the 240GB available. In spite of my specifying 8 threads, it never used more than one. Any ideas?

**Comment by sei-eschwartz** [comment]
Our use of Prolog is single threaded.  There is some Prolog support for multi-threading, and the maintainer of SWI Prolog may have some interesting in helping us improve that, but that's in the far future.

Now as for the `Aborting...` from XSB, I have not seen that before.  Looking at the source it comes from calling `abort` which we don't do.  My first guess would be some type of resource issue.  Make sure that `ulimit` is not limiting anything such as stack or heap size.

Do you have the `.facts` file?  We can rerun it with more debugging information to see if the same thing happens for us.

Also, @sei-ccohen are very close on releasing the Prolog based JSON exporter.  This would allow you to use SWI Prolog, which is much faster as the warning message suggests.

**Comment by janbbeck** [comment]
Here the facts file:
[V9facts.zip](https://github.com/cmu-sei/pharos/files/4688962/V9facts.zip)

so what does the 'threads' parameter actually do?

additionally, I had the same program run on a desktop, and it turns out that it, too, died with a similar but different message:
```
OOAN[ERROR]: Found only 49756 functions of 49805 specifically requested for analysis.
OPTI[INFO ]: Function analysis complete, analyzed 49756 functions in 15724.3 seconds.
Warning: In assert to trigger_fact/1, an index hash chain is very long; consider using asserta, multi or no index.
PLOG[ERROR]: OOAnalyzer has been running for over an hour in Prolog mode.  We have found that for, complex executables, SWI Prolog often outperforms XSB Prolog.  You may wish to dump the .facts file for your executable using the -F option of ooanalyzer, and then run the oodebugrun-swipl script in share/pharos/oorules of your build directory.  You will need to install swipl and ensure it is on your PATH.
OOAN[FATAL]: XSB Error: resource_error/++Error[XSB/Runtime/P]: [Resource (memory)] [Query exhausted system memory, (currently expanding trail/choice point stack space)]
OOAN[ERROR]: Failed to import object oriented results into Pharos.
OPTI[ERROR]: No C++ classes were detected in the program.
OPTI[INFO ]: Successfully exported to JSON file 'v9.json'.
OPTI[INFO ]: OOAnalyzer analysis complete.
```

**Comment by sei-eschwartz** [comment]
Other parts of Pharos are multi-threaded.  I know partitioning is, for example.  And probably the fact generation portion of OOAnalyzer.  But the Prolog part is not.

Yes, that XSB error is a bit more clear that it's a resource problem.  But error handling when you are out of resources is challenging, and so I feel like the Aborting error could also be a resources problem.

I am now running in a debug mode that will hopefully yield some more information if I can reproduce the problem.

**Comment by sei-ccohen** [comment]
Jan asked:

> so what does the 'threads' parameter actually do?

And sei-eschwartz responded:

> I know partitioning is, for example. 

Actually partitioning is _not_ multi-threaded, although there has been discussion about the topic with the ROSE developers.   Currently the "function analysis phase" is multi-threaded.  This phase is usually, but not always, the longest phase.  In OOAnalyzer, the function analysis phase is also the fact generation phase that occurs after partitioning and before Prolog OO analysis.  You can see that this phase is multi-threaded by watching the CPU usage between partitioning and OO analysis.

For large, complex programs I recommend running partitioning first with the ROSE partitioner with a serialization file, then a multi-threaded fact generation pass, then the SWI Prolog OO analysis phase, and finally an unreleased and incomplete JSON generation in Prolog phase (that we're working on).

**Comment by janbbeck** [comment]
As always, thank you all for the detailed information.

**Comment by sei-eschwartz** [comment]
Just to follow up on this, mine is still running.  So it seems likely that it's a resource problem of some type.  We are trying really hard to push an update to github today that will include `oojson`.  This will allow you to generate the JSON completely using SWI prolog, and will hopefully be much faster!

**Comment by janbbeck** [comment]
Thanks for the update! Will try this again when oojson becomes available.

**Comment by sei-ccohen** [comment]
Because this issue involved the analysis of a large executable, I encourage you to review the recently release documentation about [best practices for analyzing large programs](https://github.com/cmu-sei/pharos/tree/master/share/prolog/oorules).  This includes instructions on how to run the Prolog JSON generation step.

**Comment by janbbeck** [comment]
Thank you very much for that suggestion. In the linked document, it suggests the following command:
```./share/prolog/oorules/oodebugrun-swipl ooprog-facts.P >ooprog.log```
however, this does not seem to exist in the latest docker image
```
root@d2a708673987:/# find . -name "oodebugrun-swipl*"
./root/pharos/share/prolog/oorules/oodebugrun-swipl.in
./root/pharos/share/prolog/oorules/oodebugrun-swipl-noguess.in
./root/pharos/share/prolog/oorules/oodebugrun-swipl-nortti.in
root@d2a708673987:/# 
```
am I doing something wrong?

**Comment by sei-eschwartz** [comment]
Oops.  We did not sanity check to make sure all the right files are present in the Docker image.  We will work on that.

`oodebugrun-swipl` and `oojson` are only present in the Pharos build directory.  Unfortunately, we delete that from the container to save space, and we forgot to install them.

As a workaround, I would try to remove the "-reclaim" argument that is passed to build.bash in Dockerfile, and build your own.

**Comment by sei-eschwartz** [comment]
This is pushed and the new build is kicked off.  It can take a really long time to build the Docker image though (7 hours).

**Comment by sei-eschwartz** [comment]
I think this is solved

**Comment by janbbeck** [comment]
were you able to run this on the V9.exe without crash?

**Comment by sei-eschwartz** [comment]
Yes.. I think I sent the json to you?

**Comment by janbbeck** [comment]
Ah! I thought you used the other Prolog for that.

Thanks for all the support!

**Comment by sei-eschwartz** [comment]
I generated that using SWI Prolog.  It's unlikely that you'll be able to use XSB Prolog with your file... it's just too big.
