### ISSUE TITLE
std::out_of_range exception

### ISSUE THREAD

**Issue by xNxExOx** [cmu-sei/pharos#91]
### std::out_of_range exception
- input file: [BattleForge.exe](https://drive.google.com/file/d/1wi-PrvEtRBGVO8desjj5IESIuYEfvpQJ/view?usp=sharing)
- command: `ooanalyzer -f /dir/BattleForge.exe --partitioner-timeout 999999 --timing -j /dir/pharos.json --threads=20 --maximum-memory 200704 --serialize=/dir/BatteForge.pharos.serialize --partitioner=pharos --verbose=5`
- result: https://cdn.discordapp.com/attachments/562879368083275789/716731730664488970/unknown.png
- serialize file: [BatteForge.pharos.serialize](https://drive.google.com/file/d/1bXy3BdHLT-rKkA4qY0elg-E9Ubp7U_eV/view?usp=sharing)

We rent quite poverfull machine (_over 100 GB required_) to be able to even get this far, but unfortunatelly same error appear on multiple runs when started fresh or from "serialize" file

**Comment by sei-eschwartz** [comment]
Thanks, we will take a look at this

**Comment by sei-eschwartz** [comment]
Debugging these would be a lot easier if we dumped backtraces by default.  Thoughts @sei-ccohen @sei-mwd?

**Comment by xNxExOx** [comment]
if you can run it with debugger attached (assuming you have workstation with enough RAM) you should be able to get not only callstack, but also full context

**Comment by sei-mwd** [comment]
Just a note if you're trying to get a backtrace yourself: Pharos programs catch all errors that bubble up to `main` by default.  To turn this off, set the environment variable `PHAROS_PASS_EXCEPTIONS=1`.

**Comment by sei-eschwartz** [comment]
@xNxExOx Yes, that is what I am doing.  But judging from your log it takes 18 hours to crash.

**Comment by sei-eschwartz** [comment]
Unfortunately, because of user error (mine), my run died after partitioning.  @sei-ccohen is fairly convinced that he fixed this bug in b739ef8 so please try that.

**Comment by sei-eschwartz** [comment]
Please re-open if you're still having any trouble.

**Comment by xNxExOx** [comment]
unfortunatelly we end up with same looking [error](https://cdn.discordapp.com/attachments/562879368083275789/717687388939485234/unknown.png) 
do you want that `BatteForge.pharos2.serialize` file? it have 1.7 GB

**Comment by xNxExOx** [comment]
@sei-eschwartz I do not have permission to reopen the issue.

**Comment by sei-eschwartz** [comment]
I'll look into it.  You don't need to share the serialize file.

**Comment by sei-eschwartz** [comment]
Are you sure you rebuilt against the new version?  We added a default exception handler that prints a backtrace, which I don't see present in your error.

**Comment by xNxExOx** [comment]
we did not builded it we downloaded new image with `docker pull seipharos/pharos`

**Comment by sei-eschwartz** [comment]
Can you try to pull again?  It takes a long time to build the docker image.  It may not have been published when you pulled.

**Comment by xNxExOx** [comment]
it pulled new image, not sure if there was any other change recently.
We now trying Rose, if we will have enough time left on the expensive machine we rented, we will try again.

**Comment by sei-eschwartz** [comment]
Sorry, I confused myself.  The backtrace change wasn't in the new code released.  So don't worry about this for now and I'll look into it.

**Comment by sei-ccohen** [comment]
Because this issue involved the analysis of a large executable, I encourage you to review the recently release documentation about [best practices for analyzing large programs](https://github.com/cmu-sei/pharos/tree/master/share/prolog/oorules).

**Comment by sei-eschwartz** [comment]
I confirmed this is fixed for me now.  Reopen if you have any problems.
