### ISSUE TITLE
IDA plugin does not show

### ISSUE THREAD

**Issue by xNxExOx** [cmu-sei/pharos#95]
![obrazek](https://user-images.githubusercontent.com/1893229/83660830-9975dc80-a5c5-11ea-9536-3a24a882de63.png)
(Ghidra plugin works for me so I can continue)
the plugin is in the folder, but IDA does not list it, and F3 also does nothing.
I restarted IDA, I tried both python 2.717 and 3.8.3, but the result is same plugin does not show up.

**Comment by sei-eschwartz** [comment]
Is there anything in the scripting window?  What version of IDA?

**Comment by xNxExOx** [comment]
Pro 7.5.200519 Windows x64 (32-bit address size)
where I can find scripting window?

**Comment by xNxExOx** [comment]
```
C:\Program Files\IDA Pro 7.5\plugins\ooanalyzer.py: No module named 'six'
Traceback (most recent call last):
  File "C:\Program Files\IDA Pro 7.5\python\3\ida_idaapi.py", line 604, in IDAPython_ExecScript
    exec(code, g)
  File "C:/Program Files/IDA Pro 7.5/plugins/ooanalyzer.py", line 15, in <module>
    import six
ModuleNotFoundError: No module named 'six'
```

**Comment by xNxExOx** [comment]
now it crash IDA on start after installing with `pip install six` :(

**Comment by sei-eschwartz** [comment]
I have no idea why that would be.  IDA clearly wasn't using six because you didn't have it installed...

**Comment by sei-eschwartz** [comment]
The latest version does not depend on the `six` module anymore.  Please try it out and reopen if you continue to have problems.

**Comment by xNxExOx** [comment]
Every time IDA tries to load it will crash even with the todays version that have `python_version_2 = (sys.version_info[0] == 2)`

https://drive.google.com/file/d/1D3U7PWnH1Cimr-076Yg6HvlSadB30vog/view?usp=sharing
I tried opening new file, and it created much smaller dump, so I think it was not related to `six`
I have no idea what can be the cause, so if you want me to try something I can try it. @sei-eschwartz

**Comment by sei-eschwartz** [comment]
I don't have permission to view your link.

To help you, we need to know the error in the output window.

**Comment by xNxExOx** [comment]
sorry google now do not give read permission to shared link by default .
I can not tell you what is in output window because output window does not show

**Comment by sei-eschwartz** [comment]
Does IDA crash if you remove the `OOAnalyzer.py` file?

**Comment by xNxExOx** [comment]
no renaming the plugin to `OOAnalyzer.py0` let IDA to start normally without it.
the output window actually show, but nothing interesting in it
![obrazek](https://user-images.githubusercontent.com/1893229/83765441-76a5ff80-a67b-11ea-8134-f238a9d23242.png)

**Comment by sei-eschwartz** [comment]
I would suggest reinstalling IDA, including python 2.7.  If that doesn't work, you'll need to ask Hex-Rays for help.

**Comment by sei-eschwartz** [comment]
I am closing this because it's not something we can help with without more information.
